import { PrismaClient, ChecklistUnit, ChecklistShiftType } from '@prisma/client';

const prisma = new PrismaClient();

interface TemplateData {
  unit: ChecklistUnit;
  shiftType: ChecklistShiftType;
  section: string;
  sectionTitle: string;
  itemNumber: number;
  title: string;
  description?: string;
  toolSystem?: string;
  timeSlot?: string;
  isRequired: boolean;
  order: number;
}

// ============================================
// IT OPERATIONS - HARIAN_KANTOR (08:00-17:00)
// From: 06_Checklist_Harian_IT_Template_Shift.xlsx
// ============================================

const IT_OPS_HARIAN_TEMPLATES: TemplateData[] = [
  // Section A: MONITORING AWAL HARI (07:00 - 08:00)
  {
    unit: 'IT_OPERATIONS',
    shiftType: 'HARIAN_KANTOR',
    section: 'A',
    sectionTitle: 'MONITORING AWAL HARI (07:00 - 08:00)',
    itemNumber: 1,
    title: 'Cek status semua server via Grafana (100 VM + 30 Fisik)',
    toolSystem: 'Grafana/Prometheus',
    timeSlot: '07:00',
    isRequired: true,
    order: 1,
  },
  {
    unit: 'IT_OPERATIONS',
    shiftType: 'HARIAN_KANTOR',
    section: 'A',
    sectionTitle: 'MONITORING AWAL HARI (07:00 - 08:00)',
    itemNumber: 2,
    title: 'Verifikasi CPU, Memory, Disk usage tidak melebihi threshold (>80%)',
    toolSystem: 'Grafana',
    timeSlot: '07:00',
    isRequired: true,
    order: 2,
  },
  {
    unit: 'IT_OPERATIONS',
    shiftType: 'HARIAN_KANTOR',
    section: 'A',
    sectionTitle: 'MONITORING AWAL HARI (07:00 - 08:00)',
    itemNumber: 3,
    title: 'Cek status konektivitas DC Tekno dan Ruang Server SMS',
    toolSystem: 'Grafana',
    timeSlot: '07:00',
    isRequired: true,
    order: 3,
  },
  {
    unit: 'IT_OPERATIONS',
    shiftType: 'HARIAN_KANTOR',
    section: 'A',
    sectionTitle: 'MONITORING AWAL HARI (07:00 - 08:00)',
    itemNumber: 4,
    title: 'Review alert Prometheus dari semalam (jika ada)',
    toolSystem: 'Prometheus Alerts',
    timeSlot: '07:00',
    isRequired: false,
    order: 4,
  },
  {
    unit: 'IT_OPERATIONS',
    shiftType: 'HARIAN_KANTOR',
    section: 'A',
    sectionTitle: 'MONITORING AWAL HARI (07:00 - 08:00)',
    itemNumber: 5,
    title: 'Cek backup seluruh database yang di-maintain internal berhasil',
    toolSystem: 'Backup System',
    timeSlot: '07:00',
    isRequired: true,
    order: 5,
  },
  {
    unit: 'IT_OPERATIONS',
    shiftType: 'HARIAN_KANTOR',
    section: 'A',
    sectionTitle: 'MONITORING AWAL HARI (07:00 - 08:00)',
    itemNumber: 6,
    title: 'Verifikasi database BSGQRIS berjalan normal',
    toolSystem: 'Grafana/Loki',
    timeSlot: '08:00',
    isRequired: true,
    order: 6,
  },
  {
    unit: 'IT_OPERATIONS',
    shiftType: 'HARIAN_KANTOR',
    section: 'A',
    sectionTitle: 'MONITORING AWAL HARI (07:00 - 08:00)',
    itemNumber: 7,
    title: 'Cek file staging dari vendor CIP sudah diterima di file server',
    toolSystem: 'File Server',
    timeSlot: '07:00',
    isRequired: true,
    order: 7,
  },
  {
    unit: 'IT_OPERATIONS',
    shiftType: 'HARIAN_KANTOR',
    section: 'A',
    sectionTitle: 'MONITORING AWAL HARI (07:00 - 08:00)',
    itemNumber: 8,
    title: 'Verifikasi report EOD sudah lengkap untuk Antasena dan OBOX',
    toolSystem: 'File Server',
    timeSlot: '07:00',
    isRequired: true,
    order: 8,
  },

  // Section B: MONITORING SISTEM KRITIKAL (08:00 - 09:00)
  {
    unit: 'IT_OPERATIONS',
    shiftType: 'HARIAN_KANTOR',
    section: 'B',
    sectionTitle: 'MONITORING SISTEM KRITIKAL (08:00 - 09:00)',
    itemNumber: 1,
    title: 'Cek status koneksi BI-FAST',
    toolSystem: 'Middleware Dashboard',
    timeSlot: '08:00',
    isRequired: true,
    order: 1,
  },
  {
    unit: 'IT_OPERATIONS',
    shiftType: 'HARIAN_KANTOR',
    section: 'B',
    sectionTitle: 'MONITORING SISTEM KRITIKAL (08:00 - 09:00)',
    itemNumber: 2,
    title: 'Cek status koneksi Artajasa (ATM/Debit)',
    toolSystem: 'Middleware Dashboard',
    timeSlot: '08:00',
    isRequired: true,
    order: 2,
  },
  {
    unit: 'IT_OPERATIONS',
    shiftType: 'HARIAN_KANTOR',
    section: 'B',
    sectionTitle: 'MONITORING SISTEM KRITIKAL (08:00 - 09:00)',
    itemNumber: 3,
    title: 'Cek status koneksi Finnet',
    toolSystem: 'Middleware Dashboard',
    timeSlot: '08:00',
    isRequired: true,
    order: 3,
  },
  {
    unit: 'IT_OPERATIONS',
    shiftType: 'HARIAN_KANTOR',
    section: 'B',
    sectionTitle: 'MONITORING SISTEM KRITIKAL (08:00 - 09:00)',
    itemNumber: 4,
    title: 'Cek status koneksi Pajak',
    toolSystem: 'Middleware Dashboard',
    timeSlot: '08:00',
    isRequired: true,
    order: 4,
  },
  {
    unit: 'IT_OPERATIONS',
    shiftType: 'HARIAN_KANTOR',
    section: 'B',
    sectionTitle: 'MONITORING SISTEM KRITIKAL (08:00 - 09:00)',
    itemNumber: 5,
    title: 'Cek status koneksi Kementerian',
    toolSystem: 'Middleware Dashboard',
    timeSlot: '08:00',
    isRequired: true,
    order: 5,
  },
  {
    unit: 'IT_OPERATIONS',
    shiftType: 'HARIAN_KANTOR',
    section: 'B',
    sectionTitle: 'MONITORING SISTEM KRITIKAL (08:00 - 09:00)',
    itemNumber: 6,
    title: 'Cek status koneksi PBB Pemerintah Daerah',
    toolSystem: 'Middleware Dashboard',
    timeSlot: '08:00',
    isRequired: true,
    order: 6,
  },
  {
    unit: 'IT_OPERATIONS',
    shiftType: 'HARIAN_KANTOR',
    section: 'B',
    sectionTitle: 'MONITORING SISTEM KRITIKAL (08:00 - 09:00)',
    itemNumber: 7,
    title: 'Cek status BSGTouch via aplikasi mobile (managed vendor CIP)',
    toolSystem: 'BSGTouch App',
    timeSlot: '08:00',
    isRequired: true,
    order: 7,
  },
  {
    unit: 'IT_OPERATIONS',
    shiftType: 'HARIAN_KANTOR',
    section: 'B',
    sectionTitle: 'MONITORING SISTEM KRITIKAL (08:00 - 09:00)',
    itemNumber: 8,
    title: 'Cek status BSGQRIS',
    toolSystem: 'Grafana/Loki',
    timeSlot: '08:00',
    isRequired: true,
    order: 8,
  },
  {
    unit: 'IT_OPERATIONS',
    shiftType: 'HARIAN_KANTOR',
    section: 'B',
    sectionTitle: 'MONITORING SISTEM KRITIKAL (08:00 - 09:00)',
    itemNumber: 9,
    title: 'Cek status ATM Switching',
    toolSystem: 'Grafana',
    timeSlot: '08:00',
    isRequired: true,
    order: 9,
  },
  {
    unit: 'IT_OPERATIONS',
    shiftType: 'HARIAN_KANTOR',
    section: 'B',
    sectionTitle: 'MONITORING SISTEM KRITIKAL (08:00 - 09:00)',
    itemNumber: 10,
    title: 'Cek uptime aplikasi surrounding',
    toolSystem: 'Grafana',
    timeSlot: '08:00',
    isRequired: true,
    order: 10,
  },
  {
    unit: 'IT_OPERATIONS',
    shiftType: 'HARIAN_KANTOR',
    section: 'B',
    sectionTitle: 'MONITORING SISTEM KRITIKAL (08:00 - 09:00)',
    itemNumber: 11,
    title: 'Cek grafik transaksi di Loki Stack (hijau = sukses, lainnya = error)',
    description: 'Monitor secara berkala',
    toolSystem: 'Loki Stack',
    isRequired: true,
    order: 11,
  },
  {
    unit: 'IT_OPERATIONS',
    shiftType: 'HARIAN_KANTOR',
    section: 'B',
    sectionTitle: 'MONITORING SISTEM KRITIKAL (08:00 - 09:00)',
    itemNumber: 12,
    title: 'Review anomali transaksi jika ada indikasi error',
    toolSystem: 'Loki Stack',
    isRequired: false,
    order: 12,
  },
  {
    unit: 'IT_OPERATIONS',
    shiftType: 'HARIAN_KANTOR',
    section: 'B',
    sectionTitle: 'MONITORING SISTEM KRITIKAL (08:00 - 09:00)',
    itemNumber: 13,
    title: 'Cek status alert mesin ATM via XMonitor',
    toolSystem: 'XMonitor',
    timeSlot: '08:00',
    isRequired: true,
    order: 13,
  },
  {
    unit: 'IT_OPERATIONS',
    shiftType: 'HARIAN_KANTOR',
    section: 'B',
    sectionTitle: 'MONITORING SISTEM KRITIKAL (08:00 - 09:00)',
    itemNumber: 14,
    title: 'Infokan ke Group WhatsApp jika ada ATM bermasalah',
    toolSystem: 'WhatsApp',
    isRequired: false,
    order: 14,
  },

  // Section C: MONITORING BERKALA (Setiap 2 Jam)
  // These are periodic items that repeat at 08:00, 10:00, 12:00, 14:00, 16:00, 18:00
  {
    unit: 'IT_OPERATIONS',
    shiftType: 'HARIAN_KANTOR',
    section: 'C',
    sectionTitle: 'MONITORING BERKALA (Setiap 2 Jam)',
    itemNumber: 1,
    title: 'Monitoring uptime aplikasi kritikal',
    toolSystem: 'Grafana',
    timeSlot: '08:00',
    isRequired: true,
    order: 1,
  },
  {
    unit: 'IT_OPERATIONS',
    shiftType: 'HARIAN_KANTOR',
    section: 'C',
    sectionTitle: 'MONITORING BERKALA (Setiap 2 Jam)',
    itemNumber: 2,
    title: 'Monitoring uptime aplikasi surrounding',
    toolSystem: 'Grafana',
    timeSlot: '08:00',
    isRequired: true,
    order: 2,
  },
  {
    unit: 'IT_OPERATIONS',
    shiftType: 'HARIAN_KANTOR',
    section: 'C',
    sectionTitle: 'MONITORING BERKALA (Setiap 2 Jam)',
    itemNumber: 3,
    title: 'Monitoring metrics server via Grafana',
    toolSystem: 'Grafana',
    timeSlot: '08:00',
    isRequired: true,
    order: 3,
  },
  {
    unit: 'IT_OPERATIONS',
    shiftType: 'HARIAN_KANTOR',
    section: 'C',
    sectionTitle: 'MONITORING BERKALA (Setiap 2 Jam)',
    itemNumber: 4,
    title: 'Cek grafik transaksi Loki Stack',
    toolSystem: 'Loki Stack',
    timeSlot: '08:00',
    isRequired: true,
    order: 4,
  },
  {
    unit: 'IT_OPERATIONS',
    shiftType: 'HARIAN_KANTOR',
    section: 'C',
    sectionTitle: 'MONITORING BERKALA (Setiap 2 Jam)',
    itemNumber: 5,
    title: 'Cek status alert ATM via XMonitor',
    toolSystem: 'XMonitor',
    timeSlot: '08:00',
    isRequired: true,
    order: 5,
  },
  {
    unit: 'IT_OPERATIONS',
    shiftType: 'HARIAN_KANTOR',
    section: 'C',
    sectionTitle: 'MONITORING BERKALA (Setiap 2 Jam)',
    itemNumber: 6,
    title: 'Cek koneksi Host to Host tetap aktif',
    toolSystem: 'Middleware Dashboard',
    timeSlot: '08:00',
    isRequired: true,
    order: 6,
  },

  // Section D: PENUTUPAN HARI (16:00 - 17:00)
  {
    unit: 'IT_OPERATIONS',
    shiftType: 'HARIAN_KANTOR',
    section: 'D',
    sectionTitle: 'PENUTUPAN HARI (16:00 - 17:00)',
    itemNumber: 1,
    title: 'Verifikasi seluruh cabang sudah berhasil close',
    toolSystem: 'Core Banking',
    timeSlot: '16:00',
    isRequired: true,
    order: 1,
  },
  {
    unit: 'IT_OPERATIONS',
    shiftType: 'HARIAN_KANTOR',
    section: 'D',
    sectionTitle: 'PENUTUPAN HARI (16:00 - 17:00)',
    itemNumber: 2,
    title: 'Catat issue/anomali yang perlu follow up di ServiceDesk',
    toolSystem: 'ServiceDesk',
    timeSlot: '16:00',
    isRequired: false,
    order: 2,
  },
  {
    unit: 'IT_OPERATIONS',
    shiftType: 'HARIAN_KANTOR',
    section: 'D',
    sectionTitle: 'PENUTUPAN HARI (16:00 - 17:00)',
    itemNumber: 3,
    title: 'Submit laporan harian ke Pemimpin Departemen',
    toolSystem: 'Email/Report',
    timeSlot: '17:00',
    isRequired: true,
    order: 3,
  },
];

// ============================================
// MONITORING - SHIFT_MALAM (20:00-08:00)
// From: 06_Checklist_PIC_P2OT_Template_Shift.xlsx - Shift Malam
// ============================================

const MONITORING_SHIFT_MALAM_TEMPLATES: TemplateData[] = [
  // Section A: SERAH TERIMA & MULAI SHIFT (20:00 - 20:30)
  {
    unit: 'MONITORING',
    shiftType: 'SHIFT_MALAM',
    section: 'A',
    sectionTitle: 'SERAH TERIMA & MULAI SHIFT (20:00 - 20:30)',
    itemNumber: 1,
    title: 'Terima handover dari PIC Standby / Shift Siang (weekend)',
    description: 'Baca catatan shift sebelumnya',
    timeSlot: '20:00',
    isRequired: true,
    order: 1,
  },
  {
    unit: 'MONITORING',
    shiftType: 'SHIFT_MALAM',
    section: 'A',
    sectionTitle: 'SERAH TERIMA & MULAI SHIFT (20:00 - 20:30)',
    itemNumber: 2,
    title: 'Review log insiden & eskalasi dari shift sebelumnya',
    toolSystem: 'ServiceDesk',
    timeSlot: '20:00',
    isRequired: true,
    order: 2,
  },
  {
    unit: 'MONITORING',
    shiftType: 'SHIFT_MALAM',
    section: 'A',
    sectionTitle: 'SERAH TERIMA & MULAI SHIFT (20:00 - 20:30)',
    itemNumber: 3,
    title: 'Verifikasi status semua sistem kritikal (hijau/merah)',
    toolSystem: 'Grafana Dashboard',
    timeSlot: '20:00',
    isRequired: true,
    order: 3,
  },
  {
    unit: 'MONITORING',
    shiftType: 'SHIFT_MALAM',
    section: 'A',
    sectionTitle: 'SERAH TERIMA & MULAI SHIFT (20:00 - 20:30)',
    itemNumber: 4,
    title: 'Konfirmasi buddy on-call tersedia & reachable',
    description: 'Catat nama buddy',
    toolSystem: 'WhatsApp',
    timeSlot: '20:00',
    isRequired: true,
    order: 4,
  },

  // Section B: MONITORING RUTIN MALAM (Setiap 2 Jam: 22:00, 00:00, 02:00, 04:00, 06:00)
  {
    unit: 'MONITORING',
    shiftType: 'SHIFT_MALAM',
    section: 'B',
    sectionTitle: 'MONITORING RUTIN MALAM (Setiap 2 Jam)',
    itemNumber: 1,
    title: 'Cek status semua server via Grafana (VM + Fisik)',
    description: 'CPU, Memory, Disk < 80%',
    toolSystem: 'Grafana/Prometheus',
    timeSlot: '22:00',
    isRequired: true,
    order: 1,
  },
  {
    unit: 'MONITORING',
    shiftType: 'SHIFT_MALAM',
    section: 'B',
    sectionTitle: 'MONITORING RUTIN MALAM (Setiap 2 Jam)',
    itemNumber: 2,
    title: 'Verifikasi konektivitas DC Tekno dan Ruang Server SMS',
    toolSystem: 'Grafana',
    timeSlot: '22:00',
    isRequired: true,
    order: 2,
  },
  {
    unit: 'MONITORING',
    shiftType: 'SHIFT_MALAM',
    section: 'B',
    sectionTitle: 'MONITORING RUTIN MALAM (Setiap 2 Jam)',
    itemNumber: 3,
    title: 'Review alert Prometheus - ada alert baru?',
    toolSystem: 'Prometheus Alerts',
    timeSlot: '22:00',
    isRequired: true,
    order: 3,
  },
  {
    unit: 'MONITORING',
    shiftType: 'SHIFT_MALAM',
    section: 'B',
    sectionTitle: 'MONITORING RUTIN MALAM (Setiap 2 Jam)',
    itemNumber: 4,
    title: 'Cek status koneksi Host-to-Host (BI-FAST, Artajasa, Finnet, Pajak, Kementerian, PBB)',
    toolSystem: 'Middleware Dashboard',
    timeSlot: '22:00',
    isRequired: true,
    order: 4,
  },
  {
    unit: 'MONITORING',
    shiftType: 'SHIFT_MALAM',
    section: 'B',
    sectionTitle: 'MONITORING RUTIN MALAM (Setiap 2 Jam)',
    itemNumber: 5,
    title: 'Cek status ATM via XMonitor - infokan ke Group WA jika bermasalah',
    toolSystem: 'XMonitor',
    timeSlot: '22:00',
    isRequired: true,
    order: 5,
  },
  {
    unit: 'MONITORING',
    shiftType: 'SHIFT_MALAM',
    section: 'B',
    sectionTitle: 'MONITORING RUTIN MALAM (Setiap 2 Jam)',
    itemNumber: 6,
    title: 'Cek status BSGTouch via aplikasi mobile',
    toolSystem: 'BSGTouch App',
    timeSlot: '22:00',
    isRequired: true,
    order: 6,
  },
  {
    unit: 'MONITORING',
    shiftType: 'SHIFT_MALAM',
    section: 'B',
    sectionTitle: 'MONITORING RUTIN MALAM (Setiap 2 Jam)',
    itemNumber: 7,
    title: 'Cek status BSGQRIS',
    toolSystem: 'Grafana/Loki',
    timeSlot: '22:00',
    isRequired: true,
    order: 7,
  },
  {
    unit: 'MONITORING',
    shiftType: 'SHIFT_MALAM',
    section: 'B',
    sectionTitle: 'MONITORING RUTIN MALAM (Setiap 2 Jam)',
    itemNumber: 8,
    title: 'Cek grafik transaksi di Loki Stack (hijau = sukses)',
    toolSystem: 'Loki Stack',
    timeSlot: '22:00',
    isRequired: true,
    order: 8,
  },

  // Section C: MONITORING EOD & BACKUP (00:00 - 04:00)
  {
    unit: 'MONITORING',
    shiftType: 'SHIFT_MALAM',
    section: 'C',
    sectionTitle: 'MONITORING EOD & BACKUP (00:00 - 04:00)',
    itemNumber: 1,
    title: 'Monitoring proses EOD dari vendor CIP',
    description: 'Biasanya 00:00-02:00',
    toolSystem: 'Koordinasi CIP',
    timeSlot: '00:00',
    isRequired: true,
    order: 1,
  },
  {
    unit: 'MONITORING',
    shiftType: 'SHIFT_MALAM',
    section: 'C',
    sectionTitle: 'MONITORING EOD & BACKUP (00:00 - 04:00)',
    itemNumber: 2,
    title: 'Verifikasi backup database berhasil',
    toolSystem: 'Backup System',
    timeSlot: '02:00',
    isRequired: true,
    order: 2,
  },
  {
    unit: 'MONITORING',
    shiftType: 'SHIFT_MALAM',
    section: 'C',
    sectionTitle: 'MONITORING EOD & BACKUP (00:00 - 04:00)',
    itemNumber: 3,
    title: 'Cek file staging dari vendor CIP sudah diterima',
    toolSystem: 'File Server',
    timeSlot: '04:00',
    isRequired: true,
    order: 3,
  },
  {
    unit: 'MONITORING',
    shiftType: 'SHIFT_MALAM',
    section: 'C',
    sectionTitle: 'MONITORING EOD & BACKUP (00:00 - 04:00)',
    itemNumber: 4,
    title: 'Verifikasi report EOD lengkap (Antasena, OBOX)',
    toolSystem: 'File Server',
    timeSlot: '04:00',
    isRequired: true,
    order: 4,
  },

  // Section D: PERSIAPAN AKHIR SHIFT (06:00 - 08:00)
  {
    unit: 'MONITORING',
    shiftType: 'SHIFT_MALAM',
    section: 'D',
    sectionTitle: 'PERSIAPAN AKHIR SHIFT (06:00 - 08:00)',
    itemNumber: 1,
    title: 'Final check semua sistem sebelum handover',
    toolSystem: 'All Dashboards',
    timeSlot: '06:00',
    isRequired: true,
    order: 1,
  },
  {
    unit: 'MONITORING',
    shiftType: 'SHIFT_MALAM',
    section: 'D',
    sectionTitle: 'PERSIAPAN AKHIR SHIFT (06:00 - 08:00)',
    itemNumber: 2,
    title: 'Kompilasi catatan insiden & eskalasi malam ini',
    toolSystem: 'ServiceDesk',
    timeSlot: '06:00',
    isRequired: true,
    order: 2,
  },
  {
    unit: 'MONITORING',
    shiftType: 'SHIFT_MALAM',
    section: 'D',
    sectionTitle: 'PERSIAPAN AKHIR SHIFT (06:00 - 08:00)',
    itemNumber: 3,
    title: 'Siapkan summary shift untuk handover pagi',
    description: 'Tulis di kolom Keterangan',
    timeSlot: '07:00',
    isRequired: true,
    order: 3,
  },
  {
    unit: 'MONITORING',
    shiftType: 'SHIFT_MALAM',
    section: 'D',
    sectionTitle: 'PERSIAPAN AKHIR SHIFT (06:00 - 08:00)',
    itemNumber: 4,
    title: 'Serah terima ke tim kantor (weekday) atau PIC Shift Siang (weekend)',
    description: 'Pastikan no open issues',
    timeSlot: '08:00',
    isRequired: true,
    order: 4,
  },
];

// ============================================
// MONITORING - STANDBY_LEMBUR (17:00-20:00)
// From: 06_Checklist_PIC_P2OT_Template_Shift.xlsx - Standby Lembur
// ============================================

const MONITORING_STANDBY_LEMBUR_TEMPLATES: TemplateData[] = [
  // Section A: TRANSISI DARI JAM KANTOR (17:00 - 17:30)
  {
    unit: 'MONITORING',
    shiftType: 'STANDBY_LEMBUR',
    section: 'A',
    sectionTitle: 'TRANSISI DARI JAM KANTOR (17:00 - 17:30)',
    itemNumber: 1,
    title: 'Konfirmasi kehadiran sebagai PIC Standby',
    description: 'Lapor ke Koordinator Shift',
    timeSlot: '17:00',
    isRequired: true,
    order: 1,
  },
  {
    unit: 'MONITORING',
    shiftType: 'STANDBY_LEMBUR',
    section: 'A',
    sectionTitle: 'TRANSISI DARI JAM KANTOR (17:00 - 17:30)',
    itemNumber: 2,
    title: 'Review status sistem dari tim kantor - ada issue pending?',
    toolSystem: 'ServiceDesk',
    timeSlot: '17:00',
    isRequired: true,
    order: 2,
  },
  {
    unit: 'MONITORING',
    shiftType: 'STANDBY_LEMBUR',
    section: 'A',
    sectionTitle: 'TRANSISI DARI JAM KANTOR (17:00 - 17:30)',
    itemNumber: 3,
    title: 'Cek status insiden yang belum selesai dari jam kantor',
    description: 'Prioritaskan penyelesaian',
    toolSystem: 'ServiceDesk',
    timeSlot: '17:00',
    isRequired: true,
    order: 3,
  },

  // Section B: MONITORING SORE (17:30 - 19:30)
  {
    unit: 'MONITORING',
    shiftType: 'STANDBY_LEMBUR',
    section: 'B',
    sectionTitle: 'MONITORING SORE (17:30 - 19:30)',
    itemNumber: 1,
    title: 'Monitoring sistem kritikal - pastikan semua cabang sudah close',
    description: 'Biasanya selesai ~18:00',
    toolSystem: 'Core Banking',
    timeSlot: '17:30',
    isRequired: true,
    order: 1,
  },
  {
    unit: 'MONITORING',
    shiftType: 'STANDBY_LEMBUR',
    section: 'B',
    sectionTitle: 'MONITORING SORE (17:30 - 19:30)',
    itemNumber: 2,
    title: 'Cek grafik transaksi akhir hari - ada anomali?',
    toolSystem: 'Loki Stack',
    timeSlot: '18:00',
    isRequired: true,
    order: 2,
  },
  {
    unit: 'MONITORING',
    shiftType: 'STANDBY_LEMBUR',
    section: 'B',
    sectionTitle: 'MONITORING SORE (17:30 - 19:30)',
    itemNumber: 3,
    title: 'Cek status koneksi Host-to-Host',
    description: 'BI-FAST, Artajasa, dll.',
    toolSystem: 'Middleware Dashboard',
    timeSlot: '18:00',
    isRequired: true,
    order: 3,
  },
  {
    unit: 'MONITORING',
    shiftType: 'STANDBY_LEMBUR',
    section: 'B',
    sectionTitle: 'MONITORING SORE (17:30 - 19:30)',
    itemNumber: 4,
    title: 'Cek status ATM - infokan jika bermasalah',
    toolSystem: 'XMonitor',
    timeSlot: '18:00',
    isRequired: true,
    order: 4,
  },

  // Section C: SERAH TERIMA KE SHIFT MALAM (19:30 - 20:00)
  {
    unit: 'MONITORING',
    shiftType: 'STANDBY_LEMBUR',
    section: 'C',
    sectionTitle: 'SERAH TERIMA KE SHIFT MALAM (19:30 - 20:00)',
    itemNumber: 1,
    title: 'Kompilasi catatan & status sistem untuk handover',
    timeSlot: '19:30',
    isRequired: true,
    order: 1,
  },
  {
    unit: 'MONITORING',
    shiftType: 'STANDBY_LEMBUR',
    section: 'C',
    sectionTitle: 'SERAH TERIMA KE SHIFT MALAM (19:30 - 20:00)',
    itemNumber: 2,
    title: 'Handover ke PIC Shift Malam - brief kondisi terkini',
    description: 'Highlight open issues',
    timeSlot: '19:45',
    isRequired: true,
    order: 2,
  },
  {
    unit: 'MONITORING',
    shiftType: 'STANDBY_LEMBUR',
    section: 'C',
    sectionTitle: 'SERAH TERIMA KE SHIFT MALAM (19:30 - 20:00)',
    itemNumber: 3,
    title: 'Konfirmasi PIC Malam sudah siap & log handover',
    description: 'Tanda tangan berdua',
    timeSlot: '20:00',
    isRequired: true,
    order: 3,
  },
];

// ============================================
// MONITORING - SHIFT_SIANG_WEEKEND (08:00-20:00)
// From: 06_Checklist_PIC_P2OT_Template_Shift.xlsx - Shift Siang Weekend
// ============================================

const MONITORING_SHIFT_SIANG_WEEKEND_TEMPLATES: TemplateData[] = [
  // Section A: SERAH TERIMA & MULAI SHIFT (08:00 - 08:30)
  {
    unit: 'MONITORING',
    shiftType: 'SHIFT_SIANG_WEEKEND',
    section: 'A',
    sectionTitle: 'SERAH TERIMA & MULAI SHIFT (08:00 - 08:30)',
    itemNumber: 1,
    title: 'Terima handover dari PIC Shift Malam',
    description: 'Baca catatan shift malam',
    timeSlot: '08:00',
    isRequired: true,
    order: 1,
  },
  {
    unit: 'MONITORING',
    shiftType: 'SHIFT_SIANG_WEEKEND',
    section: 'A',
    sectionTitle: 'SERAH TERIMA & MULAI SHIFT (08:00 - 08:30)',
    itemNumber: 2,
    title: 'Review log insiden & eskalasi dari shift malam',
    toolSystem: 'ServiceDesk',
    timeSlot: '08:00',
    isRequired: true,
    order: 2,
  },
  {
    unit: 'MONITORING',
    shiftType: 'SHIFT_SIANG_WEEKEND',
    section: 'A',
    sectionTitle: 'SERAH TERIMA & MULAI SHIFT (08:00 - 08:30)',
    itemNumber: 3,
    title: 'Verifikasi status semua sistem kritikal',
    toolSystem: 'Grafana Dashboard',
    timeSlot: '08:00',
    isRequired: true,
    order: 3,
  },
  {
    unit: 'MONITORING',
    shiftType: 'SHIFT_SIANG_WEEKEND',
    section: 'A',
    sectionTitle: 'SERAH TERIMA & MULAI SHIFT (08:00 - 08:30)',
    itemNumber: 4,
    title: 'Konfirmasi buddy on-call tersedia',
    toolSystem: 'WhatsApp',
    timeSlot: '08:00',
    isRequired: true,
    order: 4,
  },

  // Section B: MONITORING BERKALA (Setiap 2 Jam: 10:00, 12:00, 14:00, 16:00, 18:00)
  {
    unit: 'MONITORING',
    shiftType: 'SHIFT_SIANG_WEEKEND',
    section: 'B',
    sectionTitle: 'MONITORING BERKALA (Setiap 2 Jam)',
    itemNumber: 1,
    title: 'Cek status semua server via Grafana',
    description: 'CPU, Memory, Disk < 80%',
    toolSystem: 'Grafana/Prometheus',
    timeSlot: '10:00',
    isRequired: true,
    order: 1,
  },
  {
    unit: 'MONITORING',
    shiftType: 'SHIFT_SIANG_WEEKEND',
    section: 'B',
    sectionTitle: 'MONITORING BERKALA (Setiap 2 Jam)',
    itemNumber: 2,
    title: 'Cek konektivitas DC Tekno dan Ruang Server',
    toolSystem: 'Grafana',
    timeSlot: '10:00',
    isRequired: true,
    order: 2,
  },
  {
    unit: 'MONITORING',
    shiftType: 'SHIFT_SIANG_WEEKEND',
    section: 'B',
    sectionTitle: 'MONITORING BERKALA (Setiap 2 Jam)',
    itemNumber: 3,
    title: 'Cek koneksi Host-to-Host (BI-FAST, Artajasa, Finnet, Pajak, Kementerian, PBB)',
    toolSystem: 'Middleware Dashboard',
    timeSlot: '10:00',
    isRequired: true,
    order: 3,
  },
  {
    unit: 'MONITORING',
    shiftType: 'SHIFT_SIANG_WEEKEND',
    section: 'B',
    sectionTitle: 'MONITORING BERKALA (Setiap 2 Jam)',
    itemNumber: 4,
    title: 'Cek status BSGTouch, BSGQRIS, ATM Switching',
    toolSystem: 'App / Grafana / XMonitor',
    timeSlot: '10:00',
    isRequired: true,
    order: 4,
  },
  {
    unit: 'MONITORING',
    shiftType: 'SHIFT_SIANG_WEEKEND',
    section: 'B',
    sectionTitle: 'MONITORING BERKALA (Setiap 2 Jam)',
    itemNumber: 5,
    title: 'Cek grafik transaksi di Loki Stack',
    toolSystem: 'Loki Stack',
    timeSlot: '10:00',
    isRequired: true,
    order: 5,
  },
  {
    unit: 'MONITORING',
    shiftType: 'SHIFT_SIANG_WEEKEND',
    section: 'B',
    sectionTitle: 'MONITORING BERKALA (Setiap 2 Jam)',
    itemNumber: 6,
    title: 'Cek status alert ATM via XMonitor',
    toolSystem: 'XMonitor',
    timeSlot: '10:00',
    isRequired: true,
    order: 6,
  },

  // Section C: PERSIAPAN SERAH TERIMA (19:30 - 20:00)
  {
    unit: 'MONITORING',
    shiftType: 'SHIFT_SIANG_WEEKEND',
    section: 'C',
    sectionTitle: 'PERSIAPAN SERAH TERIMA (19:30 - 20:00)',
    itemNumber: 1,
    title: 'Final check semua sistem',
    toolSystem: 'All Dashboards',
    timeSlot: '19:30',
    isRequired: true,
    order: 1,
  },
  {
    unit: 'MONITORING',
    shiftType: 'SHIFT_SIANG_WEEKEND',
    section: 'C',
    sectionTitle: 'PERSIAPAN SERAH TERIMA (19:30 - 20:00)',
    itemNumber: 2,
    title: 'Kompilasi catatan insiden & status',
    toolSystem: 'ServiceDesk',
    timeSlot: '19:30',
    isRequired: true,
    order: 2,
  },
  {
    unit: 'MONITORING',
    shiftType: 'SHIFT_SIANG_WEEKEND',
    section: 'C',
    sectionTitle: 'PERSIAPAN SERAH TERIMA (19:30 - 20:00)',
    itemNumber: 3,
    title: 'Handover ke PIC Shift Malam',
    description: 'Tanda tangan berdua',
    timeSlot: '20:00',
    isRequired: true,
    order: 3,
  },
];

// ============================================
// MAIN SEED FUNCTION
// ============================================

async function seedChecklistV2Templates() {
  console.log('🌱 Starting Checklist V2 template seed...');

  // Combine all templates
  const allTemplates = [
    ...IT_OPS_HARIAN_TEMPLATES,
    ...MONITORING_SHIFT_MALAM_TEMPLATES,
    ...MONITORING_STANDBY_LEMBUR_TEMPLATES,
    ...MONITORING_SHIFT_SIANG_WEEKEND_TEMPLATES,
  ];

  console.log(`📋 Total templates to seed: ${allTemplates.length}`);

  // Clear existing templates (optional - comment out to preserve existing)
  console.log('🗑️  Clearing existing V2 templates...');
  await prisma.checklistTemplateV2.deleteMany({});

  // Insert templates
  let created = 0;
  for (const template of allTemplates) {
    await prisma.checklistTemplateV2.create({
      data: {
        unit: template.unit,
        shiftType: template.shiftType,
        section: template.section,
        sectionTitle: template.sectionTitle,
        itemNumber: template.itemNumber,
        title: template.title,
        description: template.description,
        toolSystem: template.toolSystem,
        timeSlot: template.timeSlot,
        isRequired: template.isRequired,
        order: template.order,
        isActive: true,
      },
    });
    created++;
  }

  console.log(`✅ Created ${created} templates`);

  // Summary by unit and shift type
  const summary = await prisma.checklistTemplateV2.groupBy({
    by: ['unit', 'shiftType'],
    _count: true,
  });

  console.log('\n📊 Summary by Unit/Shift:');
  for (const item of summary) {
    console.log(`   ${item.unit} / ${item.shiftType}: ${item._count} templates`);
  }

  console.log('\n✅ Checklist V2 template seed completed!');
}

// Run seed
seedChecklistV2Templates()
  .catch((e) => {
    console.error('❌ Seed error:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
