import { PrismaClient, ChecklistType, ChecklistShiftType } from '@prisma/client';

const prisma = new PrismaClient();

interface TemplateData {
  checklistType: ChecklistType;
  shiftType: ChecklistShiftType;
  section: string;
  sectionTitle: string;
  itemNumber: number;
  title: string;
  description?: string;
  toolSystem?: string;
  timeSlot?: string;
  isRequired: boolean;
  order: number;
}

// ============================================
// IT_INFRASTRUKTUR - SHIFT_SIANG (08:00-20:00)
// Server monitoring, Database, H2H, BSGTouch/BSGQRIS/ATM, Loki Stack, EOD
// ============================================

const IT_INFRA_SHIFT_SIANG_TEMPLATES: TemplateData[] = [
  // Section A: MONITORING AWAL HARI (08:00 - 09:00)
  {
    checklistType: 'IT_INFRASTRUKTUR',
    shiftType: 'SHIFT_SIANG',
    section: 'A',
    sectionTitle: 'MONITORING AWAL HARI (08:00 - 09:00)',
    itemNumber: 1,
    title: 'Cek status semua server via Grafana (100 VM + 30 Fisik)',
    toolSystem: 'Grafana/Prometheus',
    timeSlot: '08:00',
    isRequired: true,
    order: 1,
  },
  {
    checklistType: 'IT_INFRASTRUKTUR',
    shiftType: 'SHIFT_SIANG',
    section: 'A',
    sectionTitle: 'MONITORING AWAL HARI (08:00 - 09:00)',
    itemNumber: 2,
    title: 'Verifikasi CPU, Memory, Disk usage tidak melebihi threshold (>80%)',
    toolSystem: 'Grafana',
    timeSlot: '08:00',
    isRequired: true,
    order: 2,
  },
  {
    checklistType: 'IT_INFRASTRUKTUR',
    shiftType: 'SHIFT_SIANG',
    section: 'A',
    sectionTitle: 'MONITORING AWAL HARI (08:00 - 09:00)',
    itemNumber: 3,
    title: 'Cek status konektivitas DC Tekno dan Ruang Server SMS',
    toolSystem: 'Grafana',
    timeSlot: '08:00',
    isRequired: true,
    order: 3,
  },
  {
    checklistType: 'IT_INFRASTRUKTUR',
    shiftType: 'SHIFT_SIANG',
    section: 'A',
    sectionTitle: 'MONITORING AWAL HARI (08:00 - 09:00)',
    itemNumber: 4,
    title: 'Review alert Prometheus dari shift malam (jika ada)',
    toolSystem: 'Prometheus Alerts',
    timeSlot: '08:00',
    isRequired: false,
    order: 4,
  },
  {
    checklistType: 'IT_INFRASTRUKTUR',
    shiftType: 'SHIFT_SIANG',
    section: 'A',
    sectionTitle: 'MONITORING AWAL HARI (08:00 - 09:00)',
    itemNumber: 5,
    title: 'Cek backup seluruh database yang di-maintain internal berhasil',
    toolSystem: 'Backup System',
    timeSlot: '08:00',
    isRequired: true,
    order: 5,
  },
  {
    checklistType: 'IT_INFRASTRUKTUR',
    shiftType: 'SHIFT_SIANG',
    section: 'A',
    sectionTitle: 'MONITORING AWAL HARI (08:00 - 09:00)',
    itemNumber: 6,
    title: 'Verifikasi database BSGQRIS berjalan normal',
    toolSystem: 'Grafana/Loki',
    timeSlot: '08:00',
    isRequired: true,
    order: 6,
  },
  {
    checklistType: 'IT_INFRASTRUKTUR',
    shiftType: 'SHIFT_SIANG',
    section: 'A',
    sectionTitle: 'MONITORING AWAL HARI (08:00 - 09:00)',
    itemNumber: 7,
    title: 'Cek file staging dari vendor CIP sudah diterima di file server',
    toolSystem: 'File Server',
    timeSlot: '08:00',
    isRequired: true,
    order: 7,
  },
  {
    checklistType: 'IT_INFRASTRUKTUR',
    shiftType: 'SHIFT_SIANG',
    section: 'A',
    sectionTitle: 'MONITORING AWAL HARI (08:00 - 09:00)',
    itemNumber: 8,
    title: 'Verifikasi report EOD sudah lengkap untuk Antasena dan OBOX',
    toolSystem: 'File Server',
    timeSlot: '08:00',
    isRequired: true,
    order: 8,
  },

  // Section B: MONITORING SISTEM KRITIKAL (09:00 - 10:00)
  {
    checklistType: 'IT_INFRASTRUKTUR',
    shiftType: 'SHIFT_SIANG',
    section: 'B',
    sectionTitle: 'MONITORING SISTEM KRITIKAL (09:00 - 10:00)',
    itemNumber: 1,
    title: 'Cek status koneksi BI-FAST',
    toolSystem: 'Middleware Dashboard',
    timeSlot: '09:00',
    isRequired: true,
    order: 1,
  },
  {
    checklistType: 'IT_INFRASTRUKTUR',
    shiftType: 'SHIFT_SIANG',
    section: 'B',
    sectionTitle: 'MONITORING SISTEM KRITIKAL (09:00 - 10:00)',
    itemNumber: 2,
    title: 'Cek status koneksi Artajasa (ATM/Debit)',
    toolSystem: 'Middleware Dashboard',
    timeSlot: '09:00',
    isRequired: true,
    order: 2,
  },
  {
    checklistType: 'IT_INFRASTRUKTUR',
    shiftType: 'SHIFT_SIANG',
    section: 'B',
    sectionTitle: 'MONITORING SISTEM KRITIKAL (09:00 - 10:00)',
    itemNumber: 3,
    title: 'Cek status koneksi Finnet',
    toolSystem: 'Middleware Dashboard',
    timeSlot: '09:00',
    isRequired: true,
    order: 3,
  },
  {
    checklistType: 'IT_INFRASTRUKTUR',
    shiftType: 'SHIFT_SIANG',
    section: 'B',
    sectionTitle: 'MONITORING SISTEM KRITIKAL (09:00 - 10:00)',
    itemNumber: 4,
    title: 'Cek status koneksi Pajak',
    toolSystem: 'Middleware Dashboard',
    timeSlot: '09:00',
    isRequired: true,
    order: 4,
  },
  {
    checklistType: 'IT_INFRASTRUKTUR',
    shiftType: 'SHIFT_SIANG',
    section: 'B',
    sectionTitle: 'MONITORING SISTEM KRITIKAL (09:00 - 10:00)',
    itemNumber: 5,
    title: 'Cek status koneksi Kementerian',
    toolSystem: 'Middleware Dashboard',
    timeSlot: '09:00',
    isRequired: true,
    order: 5,
  },
  {
    checklistType: 'IT_INFRASTRUKTUR',
    shiftType: 'SHIFT_SIANG',
    section: 'B',
    sectionTitle: 'MONITORING SISTEM KRITIKAL (09:00 - 10:00)',
    itemNumber: 6,
    title: 'Cek status koneksi PBB Pemerintah Daerah',
    toolSystem: 'Middleware Dashboard',
    timeSlot: '09:00',
    isRequired: true,
    order: 6,
  },
  {
    checklistType: 'IT_INFRASTRUKTUR',
    shiftType: 'SHIFT_SIANG',
    section: 'B',
    sectionTitle: 'MONITORING SISTEM KRITIKAL (09:00 - 10:00)',
    itemNumber: 7,
    title: 'Cek status BSGTouch via aplikasi mobile (managed vendor CIP)',
    toolSystem: 'BSGTouch App',
    timeSlot: '09:00',
    isRequired: true,
    order: 7,
  },
  {
    checklistType: 'IT_INFRASTRUKTUR',
    shiftType: 'SHIFT_SIANG',
    section: 'B',
    sectionTitle: 'MONITORING SISTEM KRITIKAL (09:00 - 10:00)',
    itemNumber: 8,
    title: 'Cek status BSGQRIS',
    toolSystem: 'Grafana/Loki',
    timeSlot: '09:00',
    isRequired: true,
    order: 8,
  },
  {
    checklistType: 'IT_INFRASTRUKTUR',
    shiftType: 'SHIFT_SIANG',
    section: 'B',
    sectionTitle: 'MONITORING SISTEM KRITIKAL (09:00 - 10:00)',
    itemNumber: 9,
    title: 'Cek status ATM Switching',
    toolSystem: 'Grafana',
    timeSlot: '09:00',
    isRequired: true,
    order: 9,
  },
  {
    checklistType: 'IT_INFRASTRUKTUR',
    shiftType: 'SHIFT_SIANG',
    section: 'B',
    sectionTitle: 'MONITORING SISTEM KRITIKAL (09:00 - 10:00)',
    itemNumber: 10,
    title: 'Cek uptime aplikasi surrounding',
    toolSystem: 'Grafana',
    timeSlot: '09:00',
    isRequired: true,
    order: 10,
  },
  {
    checklistType: 'IT_INFRASTRUKTUR',
    shiftType: 'SHIFT_SIANG',
    section: 'B',
    sectionTitle: 'MONITORING SISTEM KRITIKAL (09:00 - 10:00)',
    itemNumber: 11,
    title: 'Cek grafik transaksi di Loki Stack (hijau = sukses, lainnya = error)',
    description: 'Monitor secara berkala',
    toolSystem: 'Loki Stack',
    isRequired: true,
    order: 11,
  },
  {
    checklistType: 'IT_INFRASTRUKTUR',
    shiftType: 'SHIFT_SIANG',
    section: 'B',
    sectionTitle: 'MONITORING SISTEM KRITIKAL (09:00 - 10:00)',
    itemNumber: 12,
    title: 'Review anomali transaksi jika ada indikasi error',
    toolSystem: 'Loki Stack',
    isRequired: false,
    order: 12,
  },
  {
    checklistType: 'IT_INFRASTRUKTUR',
    shiftType: 'SHIFT_SIANG',
    section: 'B',
    sectionTitle: 'MONITORING SISTEM KRITIKAL (09:00 - 10:00)',
    itemNumber: 13,
    title: 'Cek status alert mesin ATM via XMonitor',
    toolSystem: 'XMonitor',
    timeSlot: '09:00',
    isRequired: true,
    order: 13,
  },
  {
    checklistType: 'IT_INFRASTRUKTUR',
    shiftType: 'SHIFT_SIANG',
    section: 'B',
    sectionTitle: 'MONITORING SISTEM KRITIKAL (09:00 - 10:00)',
    itemNumber: 14,
    title: 'Infokan ke Group WhatsApp jika ada ATM bermasalah',
    toolSystem: 'WhatsApp',
    isRequired: false,
    order: 14,
  },

  // Section C: MONITORING BERKALA (Setiap 2 Jam: 10:00, 12:00, 14:00, 16:00, 18:00)
  {
    checklistType: 'IT_INFRASTRUKTUR',
    shiftType: 'SHIFT_SIANG',
    section: 'C',
    sectionTitle: 'MONITORING BERKALA (Setiap 2 Jam)',
    itemNumber: 1,
    title: 'Monitoring uptime aplikasi kritikal',
    toolSystem: 'Grafana',
    timeSlot: '10:00',
    isRequired: true,
    order: 1,
  },
  {
    checklistType: 'IT_INFRASTRUKTUR',
    shiftType: 'SHIFT_SIANG',
    section: 'C',
    sectionTitle: 'MONITORING BERKALA (Setiap 2 Jam)',
    itemNumber: 2,
    title: 'Monitoring uptime aplikasi surrounding',
    toolSystem: 'Grafana',
    timeSlot: '10:00',
    isRequired: true,
    order: 2,
  },
  {
    checklistType: 'IT_INFRASTRUKTUR',
    shiftType: 'SHIFT_SIANG',
    section: 'C',
    sectionTitle: 'MONITORING BERKALA (Setiap 2 Jam)',
    itemNumber: 3,
    title: 'Monitoring metrics server via Grafana',
    toolSystem: 'Grafana',
    timeSlot: '10:00',
    isRequired: true,
    order: 3,
  },
  {
    checklistType: 'IT_INFRASTRUKTUR',
    shiftType: 'SHIFT_SIANG',
    section: 'C',
    sectionTitle: 'MONITORING BERKALA (Setiap 2 Jam)',
    itemNumber: 4,
    title: 'Cek grafik transaksi Loki Stack',
    toolSystem: 'Loki Stack',
    timeSlot: '10:00',
    isRequired: true,
    order: 4,
  },
  {
    checklistType: 'IT_INFRASTRUKTUR',
    shiftType: 'SHIFT_SIANG',
    section: 'C',
    sectionTitle: 'MONITORING BERKALA (Setiap 2 Jam)',
    itemNumber: 5,
    title: 'Cek status alert ATM via XMonitor',
    toolSystem: 'XMonitor',
    timeSlot: '10:00',
    isRequired: true,
    order: 5,
  },
  {
    checklistType: 'IT_INFRASTRUKTUR',
    shiftType: 'SHIFT_SIANG',
    section: 'C',
    sectionTitle: 'MONITORING BERKALA (Setiap 2 Jam)',
    itemNumber: 6,
    title: 'Cek koneksi Host to Host tetap aktif',
    toolSystem: 'Middleware Dashboard',
    timeSlot: '10:00',
    isRequired: true,
    order: 6,
  },

  // Section D: PENUTUPAN SHIFT (18:00 - 20:00)
  {
    checklistType: 'IT_INFRASTRUKTUR',
    shiftType: 'SHIFT_SIANG',
    section: 'D',
    sectionTitle: 'PENUTUPAN SHIFT (18:00 - 20:00)',
    itemNumber: 1,
    title: 'Verifikasi seluruh cabang sudah berhasil close',
    toolSystem: 'Core Banking',
    timeSlot: '18:00',
    isRequired: true,
    order: 1,
  },
  {
    checklistType: 'IT_INFRASTRUKTUR',
    shiftType: 'SHIFT_SIANG',
    section: 'D',
    sectionTitle: 'PENUTUPAN SHIFT (18:00 - 20:00)',
    itemNumber: 2,
    title: 'Catat issue/anomali yang perlu follow up di ServiceDesk',
    toolSystem: 'ServiceDesk',
    timeSlot: '18:00',
    isRequired: false,
    order: 2,
  },
  {
    checklistType: 'IT_INFRASTRUKTUR',
    shiftType: 'SHIFT_SIANG',
    section: 'D',
    sectionTitle: 'PENUTUPAN SHIFT (18:00 - 20:00)',
    itemNumber: 3,
    title: 'Siapkan summary shift untuk handover ke shift malam',
    toolSystem: 'ServiceDesk',
    timeSlot: '19:00',
    isRequired: true,
    order: 3,
  },
  {
    checklistType: 'IT_INFRASTRUKTUR',
    shiftType: 'SHIFT_SIANG',
    section: 'D',
    sectionTitle: 'PENUTUPAN SHIFT (18:00 - 20:00)',
    itemNumber: 4,
    title: 'Serah terima ke PIC Shift Malam',
    description: 'Handover semua open issues',
    timeSlot: '20:00',
    isRequired: true,
    order: 4,
  },
];

// ============================================
// IT_INFRASTRUKTUR - SHIFT_MALAM (20:00-08:00)
// ============================================

const IT_INFRA_SHIFT_MALAM_TEMPLATES: TemplateData[] = [
  // Section A: SERAH TERIMA & MULAI SHIFT (20:00 - 20:30)
  {
    checklistType: 'IT_INFRASTRUKTUR',
    shiftType: 'SHIFT_MALAM',
    section: 'A',
    sectionTitle: 'SERAH TERIMA & MULAI SHIFT (20:00 - 20:30)',
    itemNumber: 1,
    title: 'Terima handover dari PIC Shift Siang',
    description: 'Baca catatan shift sebelumnya',
    timeSlot: '20:00',
    isRequired: true,
    order: 1,
  },
  {
    checklistType: 'IT_INFRASTRUKTUR',
    shiftType: 'SHIFT_MALAM',
    section: 'A',
    sectionTitle: 'SERAH TERIMA & MULAI SHIFT (20:00 - 20:30)',
    itemNumber: 2,
    title: 'Review log insiden & eskalasi dari shift sebelumnya',
    toolSystem: 'ServiceDesk',
    timeSlot: '20:00',
    isRequired: true,
    order: 2,
  },
  {
    checklistType: 'IT_INFRASTRUKTUR',
    shiftType: 'SHIFT_MALAM',
    section: 'A',
    sectionTitle: 'SERAH TERIMA & MULAI SHIFT (20:00 - 20:30)',
    itemNumber: 3,
    title: 'Verifikasi status semua sistem kritikal (hijau/merah)',
    toolSystem: 'Grafana Dashboard',
    timeSlot: '20:00',
    isRequired: true,
    order: 3,
  },
  {
    checklistType: 'IT_INFRASTRUKTUR',
    shiftType: 'SHIFT_MALAM',
    section: 'A',
    sectionTitle: 'SERAH TERIMA & MULAI SHIFT (20:00 - 20:30)',
    itemNumber: 4,
    title: 'Konfirmasi buddy on-call tersedia & reachable',
    description: 'Catat nama buddy',
    toolSystem: 'WhatsApp',
    timeSlot: '20:00',
    isRequired: true,
    order: 4,
  },

  // Section B: MONITORING RUTIN MALAM (Setiap 2 Jam: 22:00, 00:00, 02:00, 04:00, 06:00)
  {
    checklistType: 'IT_INFRASTRUKTUR',
    shiftType: 'SHIFT_MALAM',
    section: 'B',
    sectionTitle: 'MONITORING RUTIN MALAM (Setiap 2 Jam)',
    itemNumber: 1,
    title: 'Cek status semua server via Grafana (VM + Fisik)',
    description: 'CPU, Memory, Disk < 80%',
    toolSystem: 'Grafana/Prometheus',
    timeSlot: '22:00',
    isRequired: true,
    order: 1,
  },
  {
    checklistType: 'IT_INFRASTRUKTUR',
    shiftType: 'SHIFT_MALAM',
    section: 'B',
    sectionTitle: 'MONITORING RUTIN MALAM (Setiap 2 Jam)',
    itemNumber: 2,
    title: 'Verifikasi konektivitas DC Tekno dan Ruang Server SMS',
    toolSystem: 'Grafana',
    timeSlot: '22:00',
    isRequired: true,
    order: 2,
  },
  {
    checklistType: 'IT_INFRASTRUKTUR',
    shiftType: 'SHIFT_MALAM',
    section: 'B',
    sectionTitle: 'MONITORING RUTIN MALAM (Setiap 2 Jam)',
    itemNumber: 3,
    title: 'Review alert Prometheus - ada alert baru?',
    toolSystem: 'Prometheus Alerts',
    timeSlot: '22:00',
    isRequired: true,
    order: 3,
  },
  {
    checklistType: 'IT_INFRASTRUKTUR',
    shiftType: 'SHIFT_MALAM',
    section: 'B',
    sectionTitle: 'MONITORING RUTIN MALAM (Setiap 2 Jam)',
    itemNumber: 4,
    title: 'Cek status koneksi Host-to-Host (BI-FAST, Artajasa, Finnet, Pajak, Kementerian, PBB)',
    toolSystem: 'Middleware Dashboard',
    timeSlot: '22:00',
    isRequired: true,
    order: 4,
  },
  {
    checklistType: 'IT_INFRASTRUKTUR',
    shiftType: 'SHIFT_MALAM',
    section: 'B',
    sectionTitle: 'MONITORING RUTIN MALAM (Setiap 2 Jam)',
    itemNumber: 5,
    title: 'Cek status ATM via XMonitor - infokan ke Group WA jika bermasalah',
    toolSystem: 'XMonitor',
    timeSlot: '22:00',
    isRequired: true,
    order: 5,
  },
  {
    checklistType: 'IT_INFRASTRUKTUR',
    shiftType: 'SHIFT_MALAM',
    section: 'B',
    sectionTitle: 'MONITORING RUTIN MALAM (Setiap 2 Jam)',
    itemNumber: 6,
    title: 'Cek status BSGTouch via aplikasi mobile',
    toolSystem: 'BSGTouch App',
    timeSlot: '22:00',
    isRequired: true,
    order: 6,
  },
  {
    checklistType: 'IT_INFRASTRUKTUR',
    shiftType: 'SHIFT_MALAM',
    section: 'B',
    sectionTitle: 'MONITORING RUTIN MALAM (Setiap 2 Jam)',
    itemNumber: 7,
    title: 'Cek status BSGQRIS',
    toolSystem: 'Grafana/Loki',
    timeSlot: '22:00',
    isRequired: true,
    order: 7,
  },
  {
    checklistType: 'IT_INFRASTRUKTUR',
    shiftType: 'SHIFT_MALAM',
    section: 'B',
    sectionTitle: 'MONITORING RUTIN MALAM (Setiap 2 Jam)',
    itemNumber: 8,
    title: 'Cek grafik transaksi di Loki Stack (hijau = sukses)',
    toolSystem: 'Loki Stack',
    timeSlot: '22:00',
    isRequired: true,
    order: 8,
  },

  // Section C: MONITORING EOD & BACKUP (00:00 - 04:00)
  {
    checklistType: 'IT_INFRASTRUKTUR',
    shiftType: 'SHIFT_MALAM',
    section: 'C',
    sectionTitle: 'MONITORING EOD & BACKUP (00:00 - 04:00)',
    itemNumber: 1,
    title: 'Monitoring proses EOD dari vendor CIP',
    description: 'Biasanya 00:00-02:00',
    toolSystem: 'Koordinasi CIP',
    timeSlot: '00:00',
    isRequired: true,
    order: 1,
  },
  {
    checklistType: 'IT_INFRASTRUKTUR',
    shiftType: 'SHIFT_MALAM',
    section: 'C',
    sectionTitle: 'MONITORING EOD & BACKUP (00:00 - 04:00)',
    itemNumber: 2,
    title: 'Verifikasi backup database berhasil',
    toolSystem: 'Backup System',
    timeSlot: '02:00',
    isRequired: true,
    order: 2,
  },
  {
    checklistType: 'IT_INFRASTRUKTUR',
    shiftType: 'SHIFT_MALAM',
    section: 'C',
    sectionTitle: 'MONITORING EOD & BACKUP (00:00 - 04:00)',
    itemNumber: 3,
    title: 'Cek file staging dari vendor CIP sudah diterima',
    toolSystem: 'File Server',
    timeSlot: '04:00',
    isRequired: true,
    order: 3,
  },
  {
    checklistType: 'IT_INFRASTRUKTUR',
    shiftType: 'SHIFT_MALAM',
    section: 'C',
    sectionTitle: 'MONITORING EOD & BACKUP (00:00 - 04:00)',
    itemNumber: 4,
    title: 'Verifikasi report EOD lengkap (Antasena, OBOX)',
    toolSystem: 'File Server',
    timeSlot: '04:00',
    isRequired: true,
    order: 4,
  },

  // Section D: PERSIAPAN AKHIR SHIFT (06:00 - 08:00)
  {
    checklistType: 'IT_INFRASTRUKTUR',
    shiftType: 'SHIFT_MALAM',
    section: 'D',
    sectionTitle: 'PERSIAPAN AKHIR SHIFT (06:00 - 08:00)',
    itemNumber: 1,
    title: 'Final check semua sistem sebelum handover',
    toolSystem: 'All Dashboards',
    timeSlot: '06:00',
    isRequired: true,
    order: 1,
  },
  {
    checklistType: 'IT_INFRASTRUKTUR',
    shiftType: 'SHIFT_MALAM',
    section: 'D',
    sectionTitle: 'PERSIAPAN AKHIR SHIFT (06:00 - 08:00)',
    itemNumber: 2,
    title: 'Kompilasi catatan insiden & eskalasi malam ini',
    toolSystem: 'ServiceDesk',
    timeSlot: '06:00',
    isRequired: true,
    order: 2,
  },
  {
    checklistType: 'IT_INFRASTRUKTUR',
    shiftType: 'SHIFT_MALAM',
    section: 'D',
    sectionTitle: 'PERSIAPAN AKHIR SHIFT (06:00 - 08:00)',
    itemNumber: 3,
    title: 'Siapkan summary shift untuk handover pagi',
    description: 'Tulis di kolom Keterangan',
    timeSlot: '07:00',
    isRequired: true,
    order: 3,
  },
  {
    checklistType: 'IT_INFRASTRUKTUR',
    shiftType: 'SHIFT_MALAM',
    section: 'D',
    sectionTitle: 'PERSIAPAN AKHIR SHIFT (06:00 - 08:00)',
    itemNumber: 4,
    title: 'Serah terima ke PIC Shift Siang',
    description: 'Pastikan no open issues',
    timeSlot: '08:00',
    isRequired: true,
    order: 4,
  },
];

// ============================================
// KEAMANAN_SIBER - SHIFT_SIANG (08:00-20:00)
// SIEM, Firewall, Endpoint, Brute-force, Unauthorized access
// ============================================

const KKS_SHIFT_SIANG_TEMPLATES: TemplateData[] = [
  // Section A: MONITORING AWAL HARI (08:00 - 09:00)
  {
    checklistType: 'KEAMANAN_SIBER',
    shiftType: 'SHIFT_SIANG',
    section: 'A',
    sectionTitle: 'MONITORING AWAL HARI (08:00 - 09:00)',
    itemNumber: 1,
    title: 'Review SIEM Dashboard untuk alert semalam',
    toolSystem: 'SIEM Dashboard',
    timeSlot: '08:00',
    isRequired: true,
    order: 1,
  },
  {
    checklistType: 'KEAMANAN_SIBER',
    shiftType: 'SHIFT_SIANG',
    section: 'A',
    sectionTitle: 'MONITORING AWAL HARI (08:00 - 09:00)',
    itemNumber: 2,
    title: 'Cek Firewall log untuk aktivitas mencurigakan',
    toolSystem: 'Firewall Console',
    timeSlot: '08:00',
    isRequired: true,
    order: 2,
  },
  {
    checklistType: 'KEAMANAN_SIBER',
    shiftType: 'SHIFT_SIANG',
    section: 'A',
    sectionTitle: 'MONITORING AWAL HARI (08:00 - 09:00)',
    itemNumber: 3,
    title: 'Verifikasi status Endpoint Protection di semua server',
    toolSystem: 'EDR Console',
    timeSlot: '08:00',
    isRequired: true,
    order: 3,
  },
  {
    checklistType: 'KEAMANAN_SIBER',
    shiftType: 'SHIFT_SIANG',
    section: 'A',
    sectionTitle: 'MONITORING AWAL HARI (08:00 - 09:00)',
    itemNumber: 4,
    title: 'Review brute-force detection alerts',
    toolSystem: 'SIEM',
    timeSlot: '08:00',
    isRequired: true,
    order: 4,
  },
  {
    checklistType: 'KEAMANAN_SIBER',
    shiftType: 'SHIFT_SIANG',
    section: 'A',
    sectionTitle: 'MONITORING AWAL HARI (08:00 - 09:00)',
    itemNumber: 5,
    title: 'Cek unauthorized access attempt dari log AD',
    toolSystem: 'Active Directory',
    timeSlot: '08:00',
    isRequired: true,
    order: 5,
  },

  // Section B: MONITORING KEAMANAN (09:00 - 10:00)
  {
    checklistType: 'KEAMANAN_SIBER',
    shiftType: 'SHIFT_SIANG',
    section: 'B',
    sectionTitle: 'MONITORING KEAMANAN (09:00 - 10:00)',
    itemNumber: 1,
    title: 'Analisis threat intelligence feed terbaru',
    toolSystem: 'Threat Intel Platform',
    timeSlot: '09:00',
    isRequired: true,
    order: 1,
  },
  {
    checklistType: 'KEAMANAN_SIBER',
    shiftType: 'SHIFT_SIANG',
    section: 'B',
    sectionTitle: 'MONITORING KEAMANAN (09:00 - 10:00)',
    itemNumber: 2,
    title: 'Review IDS/IPS alerts',
    toolSystem: 'IDS/IPS Console',
    timeSlot: '09:00',
    isRequired: true,
    order: 2,
  },
  {
    checklistType: 'KEAMANAN_SIBER',
    shiftType: 'SHIFT_SIANG',
    section: 'B',
    sectionTitle: 'MONITORING KEAMANAN (09:00 - 10:00)',
    itemNumber: 3,
    title: 'Cek status VPN dan remote access logs',
    toolSystem: 'VPN Console',
    timeSlot: '09:00',
    isRequired: true,
    order: 3,
  },
  {
    checklistType: 'KEAMANAN_SIBER',
    shiftType: 'SHIFT_SIANG',
    section: 'B',
    sectionTitle: 'MONITORING KEAMANAN (09:00 - 10:00)',
    itemNumber: 4,
    title: 'Verifikasi certificate validity untuk aplikasi kritikal',
    toolSystem: 'Certificate Manager',
    timeSlot: '09:00',
    isRequired: true,
    order: 4,
  },

  // Section C: MONITORING BERKALA (Setiap 2 Jam)
  {
    checklistType: 'KEAMANAN_SIBER',
    shiftType: 'SHIFT_SIANG',
    section: 'C',
    sectionTitle: 'MONITORING BERKALA (Setiap 2 Jam)',
    itemNumber: 1,
    title: 'Review SIEM alerts real-time',
    toolSystem: 'SIEM Dashboard',
    timeSlot: '10:00',
    isRequired: true,
    order: 1,
  },
  {
    checklistType: 'KEAMANAN_SIBER',
    shiftType: 'SHIFT_SIANG',
    section: 'C',
    sectionTitle: 'MONITORING BERKALA (Setiap 2 Jam)',
    itemNumber: 2,
    title: 'Cek status endpoint protection dan malware detection',
    toolSystem: 'EDR Console',
    timeSlot: '10:00',
    isRequired: true,
    order: 2,
  },
  {
    checklistType: 'KEAMANAN_SIBER',
    shiftType: 'SHIFT_SIANG',
    section: 'C',
    sectionTitle: 'MONITORING BERKALA (Setiap 2 Jam)',
    itemNumber: 3,
    title: 'Monitor failed login attempts',
    toolSystem: 'SIEM/AD',
    timeSlot: '10:00',
    isRequired: true,
    order: 3,
  },
  {
    checklistType: 'KEAMANAN_SIBER',
    shiftType: 'SHIFT_SIANG',
    section: 'C',
    sectionTitle: 'MONITORING BERKALA (Setiap 2 Jam)',
    itemNumber: 4,
    title: 'Cek network anomaly detection',
    toolSystem: 'Network Monitor',
    timeSlot: '10:00',
    isRequired: true,
    order: 4,
  },

  // Section D: PENUTUPAN SHIFT (18:00 - 20:00)
  {
    checklistType: 'KEAMANAN_SIBER',
    shiftType: 'SHIFT_SIANG',
    section: 'D',
    sectionTitle: 'PENUTUPAN SHIFT (18:00 - 20:00)',
    itemNumber: 1,
    title: 'Kompilasi security incidents hari ini',
    toolSystem: 'ServiceDesk',
    timeSlot: '18:00',
    isRequired: true,
    order: 1,
  },
  {
    checklistType: 'KEAMANAN_SIBER',
    shiftType: 'SHIFT_SIANG',
    section: 'D',
    sectionTitle: 'PENUTUPAN SHIFT (18:00 - 20:00)',
    itemNumber: 2,
    title: 'Update security incident report',
    toolSystem: 'ServiceDesk',
    timeSlot: '18:00',
    isRequired: true,
    order: 2,
  },
  {
    checklistType: 'KEAMANAN_SIBER',
    shiftType: 'SHIFT_SIANG',
    section: 'D',
    sectionTitle: 'PENUTUPAN SHIFT (18:00 - 20:00)',
    itemNumber: 3,
    title: 'Siapkan handover untuk shift malam',
    toolSystem: 'ServiceDesk',
    timeSlot: '19:00',
    isRequired: true,
    order: 3,
  },
  {
    checklistType: 'KEAMANAN_SIBER',
    shiftType: 'SHIFT_SIANG',
    section: 'D',
    sectionTitle: 'PENUTUPAN SHIFT (18:00 - 20:00)',
    itemNumber: 4,
    title: 'Serah terima ke PIC Shift Malam',
    description: 'Highlight active threats',
    timeSlot: '20:00',
    isRequired: true,
    order: 4,
  },
];

// ============================================
// KEAMANAN_SIBER - SHIFT_MALAM (20:00-08:00)
// ============================================

const KKS_SHIFT_MALAM_TEMPLATES: TemplateData[] = [
  // Section A: SERAH TERIMA & MULAI SHIFT (20:00 - 20:30)
  {
    checklistType: 'KEAMANAN_SIBER',
    shiftType: 'SHIFT_MALAM',
    section: 'A',
    sectionTitle: 'SERAH TERIMA & MULAI SHIFT (20:00 - 20:30)',
    itemNumber: 1,
    title: 'Terima handover dari PIC Shift Siang',
    description: 'Review active threats',
    timeSlot: '20:00',
    isRequired: true,
    order: 1,
  },
  {
    checklistType: 'KEAMANAN_SIBER',
    shiftType: 'SHIFT_MALAM',
    section: 'A',
    sectionTitle: 'SERAH TERIMA & MULAI SHIFT (20:00 - 20:30)',
    itemNumber: 2,
    title: 'Review security incidents dari shift siang',
    toolSystem: 'ServiceDesk',
    timeSlot: '20:00',
    isRequired: true,
    order: 2,
  },
  {
    checklistType: 'KEAMANAN_SIBER',
    shiftType: 'SHIFT_MALAM',
    section: 'A',
    sectionTitle: 'SERAH TERIMA & MULAI SHIFT (20:00 - 20:30)',
    itemNumber: 3,
    title: 'Verifikasi status SIEM dan security tools',
    toolSystem: 'SIEM Dashboard',
    timeSlot: '20:00',
    isRequired: true,
    order: 3,
  },
  {
    checklistType: 'KEAMANAN_SIBER',
    shiftType: 'SHIFT_MALAM',
    section: 'A',
    sectionTitle: 'SERAH TERIMA & MULAI SHIFT (20:00 - 20:30)',
    itemNumber: 4,
    title: 'Konfirmasi buddy on-call tersedia',
    toolSystem: 'WhatsApp',
    timeSlot: '20:00',
    isRequired: true,
    order: 4,
  },

  // Section B: MONITORING RUTIN MALAM (Setiap 2 Jam)
  {
    checklistType: 'KEAMANAN_SIBER',
    shiftType: 'SHIFT_MALAM',
    section: 'B',
    sectionTitle: 'MONITORING RUTIN MALAM (Setiap 2 Jam)',
    itemNumber: 1,
    title: 'Review SIEM alerts',
    toolSystem: 'SIEM Dashboard',
    timeSlot: '22:00',
    isRequired: true,
    order: 1,
  },
  {
    checklistType: 'KEAMANAN_SIBER',
    shiftType: 'SHIFT_MALAM',
    section: 'B',
    sectionTitle: 'MONITORING RUTIN MALAM (Setiap 2 Jam)',
    itemNumber: 2,
    title: 'Cek Firewall logs untuk aktivitas mencurigakan',
    toolSystem: 'Firewall Console',
    timeSlot: '22:00',
    isRequired: true,
    order: 2,
  },
  {
    checklistType: 'KEAMANAN_SIBER',
    shiftType: 'SHIFT_MALAM',
    section: 'B',
    sectionTitle: 'MONITORING RUTIN MALAM (Setiap 2 Jam)',
    itemNumber: 3,
    title: 'Monitor brute-force dan unauthorized access',
    toolSystem: 'SIEM/AD',
    timeSlot: '22:00',
    isRequired: true,
    order: 3,
  },
  {
    checklistType: 'KEAMANAN_SIBER',
    shiftType: 'SHIFT_MALAM',
    section: 'B',
    sectionTitle: 'MONITORING RUTIN MALAM (Setiap 2 Jam)',
    itemNumber: 4,
    title: 'Cek endpoint protection status',
    toolSystem: 'EDR Console',
    timeSlot: '22:00',
    isRequired: true,
    order: 4,
  },
  {
    checklistType: 'KEAMANAN_SIBER',
    shiftType: 'SHIFT_MALAM',
    section: 'B',
    sectionTitle: 'MONITORING RUTIN MALAM (Setiap 2 Jam)',
    itemNumber: 5,
    title: 'Monitor network anomaly detection',
    toolSystem: 'Network Monitor',
    timeSlot: '22:00',
    isRequired: true,
    order: 5,
  },

  // Section C: MONITORING TENGAH MALAM (00:00 - 04:00)
  {
    checklistType: 'KEAMANAN_SIBER',
    shiftType: 'SHIFT_MALAM',
    section: 'C',
    sectionTitle: 'MONITORING TENGAH MALAM (00:00 - 04:00)',
    itemNumber: 1,
    title: 'Deep analysis SIEM logs tengah malam',
    toolSystem: 'SIEM Dashboard',
    timeSlot: '00:00',
    isRequired: true,
    order: 1,
  },
  {
    checklistType: 'KEAMANAN_SIBER',
    shiftType: 'SHIFT_MALAM',
    section: 'C',
    sectionTitle: 'MONITORING TENGAH MALAM (00:00 - 04:00)',
    itemNumber: 2,
    title: 'Review threat intelligence updates',
    toolSystem: 'Threat Intel Platform',
    timeSlot: '02:00',
    isRequired: true,
    order: 2,
  },
  {
    checklistType: 'KEAMANAN_SIBER',
    shiftType: 'SHIFT_MALAM',
    section: 'C',
    sectionTitle: 'MONITORING TENGAH MALAM (00:00 - 04:00)',
    itemNumber: 3,
    title: 'Cek scheduled security scan results',
    toolSystem: 'Vulnerability Scanner',
    timeSlot: '04:00',
    isRequired: true,
    order: 3,
  },

  // Section D: PERSIAPAN AKHIR SHIFT (06:00 - 08:00)
  {
    checklistType: 'KEAMANAN_SIBER',
    shiftType: 'SHIFT_MALAM',
    section: 'D',
    sectionTitle: 'PERSIAPAN AKHIR SHIFT (06:00 - 08:00)',
    itemNumber: 1,
    title: 'Final security status check',
    toolSystem: 'SIEM Dashboard',
    timeSlot: '06:00',
    isRequired: true,
    order: 1,
  },
  {
    checklistType: 'KEAMANAN_SIBER',
    shiftType: 'SHIFT_MALAM',
    section: 'D',
    sectionTitle: 'PERSIAPAN AKHIR SHIFT (06:00 - 08:00)',
    itemNumber: 2,
    title: 'Kompilasi security events malam ini',
    toolSystem: 'ServiceDesk',
    timeSlot: '06:00',
    isRequired: true,
    order: 2,
  },
  {
    checklistType: 'KEAMANAN_SIBER',
    shiftType: 'SHIFT_MALAM',
    section: 'D',
    sectionTitle: 'PERSIAPAN AKHIR SHIFT (06:00 - 08:00)',
    itemNumber: 3,
    title: 'Siapkan summary untuk handover pagi',
    timeSlot: '07:00',
    isRequired: true,
    order: 3,
  },
  {
    checklistType: 'KEAMANAN_SIBER',
    shiftType: 'SHIFT_MALAM',
    section: 'D',
    sectionTitle: 'PERSIAPAN AKHIR SHIFT (06:00 - 08:00)',
    itemNumber: 4,
    title: 'Serah terima ke PIC Shift Siang',
    description: 'Brief active security issues',
    timeSlot: '08:00',
    isRequired: true,
    order: 4,
  },
];

// ============================================
// FRAUD_COMPLIANCE - SHIFT_SIANG (08:00-20:00)
// FDS alerts, Suspicious transactions, LTKM, Artajasa/BI-FAST fraud
// ============================================

const FRAUD_SHIFT_SIANG_TEMPLATES: TemplateData[] = [
  // Section A: MONITORING AWAL HARI (08:00 - 09:00)
  {
    checklistType: 'FRAUD_COMPLIANCE',
    shiftType: 'SHIFT_SIANG',
    section: 'A',
    sectionTitle: 'MONITORING AWAL HARI (08:00 - 09:00)',
    itemNumber: 1,
    title: 'Review FDS alerts semalam (54 rules, 13 kategori)',
    toolSystem: 'FDS Dashboard',
    timeSlot: '08:00',
    isRequired: true,
    order: 1,
  },
  {
    checklistType: 'FRAUD_COMPLIANCE',
    shiftType: 'SHIFT_SIANG',
    section: 'A',
    sectionTitle: 'MONITORING AWAL HARI (08:00 - 09:00)',
    itemNumber: 2,
    title: 'Cek transaksi suspicious dari overnight',
    toolSystem: 'FDS Dashboard',
    timeSlot: '08:00',
    isRequired: true,
    order: 2,
  },
  {
    checklistType: 'FRAUD_COMPLIANCE',
    shiftType: 'SHIFT_SIANG',
    section: 'A',
    sectionTitle: 'MONITORING AWAL HARI (08:00 - 09:00)',
    itemNumber: 3,
    title: 'Review status LTKM tracking',
    toolSystem: 'LTKM System',
    timeSlot: '08:00',
    isRequired: true,
    order: 3,
  },
  {
    checklistType: 'FRAUD_COMPLIANCE',
    shiftType: 'SHIFT_SIANG',
    section: 'A',
    sectionTitle: 'MONITORING AWAL HARI (08:00 - 09:00)',
    itemNumber: 4,
    title: 'Cek notifikasi fraud dari Artajasa',
    toolSystem: 'Email/Dashboard',
    timeSlot: '08:00',
    isRequired: true,
    order: 4,
  },
  {
    checklistType: 'FRAUD_COMPLIANCE',
    shiftType: 'SHIFT_SIANG',
    section: 'A',
    sectionTitle: 'MONITORING AWAL HARI (08:00 - 09:00)',
    itemNumber: 5,
    title: 'Cek notifikasi fraud dari BI-FAST',
    toolSystem: 'Email/Dashboard',
    timeSlot: '08:00',
    isRequired: true,
    order: 5,
  },

  // Section B: ANALISIS FRAUD (09:00 - 10:00)
  {
    checklistType: 'FRAUD_COMPLIANCE',
    shiftType: 'SHIFT_SIANG',
    section: 'B',
    sectionTitle: 'ANALISIS FRAUD (09:00 - 10:00)',
    itemNumber: 1,
    title: 'Analisis detail transaksi high-risk yang terdeteksi',
    toolSystem: 'FDS Dashboard',
    timeSlot: '09:00',
    isRequired: true,
    order: 1,
  },
  {
    checklistType: 'FRAUD_COMPLIANCE',
    shiftType: 'SHIFT_SIANG',
    section: 'B',
    sectionTitle: 'ANALISIS FRAUD (09:00 - 10:00)',
    itemNumber: 2,
    title: 'Verifikasi false positive dari FDS alerts',
    toolSystem: 'FDS Dashboard',
    timeSlot: '09:00',
    isRequired: true,
    order: 2,
  },
  {
    checklistType: 'FRAUD_COMPLIANCE',
    shiftType: 'SHIFT_SIANG',
    section: 'B',
    sectionTitle: 'ANALISIS FRAUD (09:00 - 10:00)',
    itemNumber: 3,
    title: 'Follow up case fraud yang pending',
    toolSystem: 'Case Management',
    timeSlot: '09:00',
    isRequired: true,
    order: 3,
  },
  {
    checklistType: 'FRAUD_COMPLIANCE',
    shiftType: 'SHIFT_SIANG',
    section: 'B',
    sectionTitle: 'ANALISIS FRAUD (09:00 - 10:00)',
    itemNumber: 4,
    title: 'Update status LTKM jika ada perubahan',
    toolSystem: 'LTKM System',
    timeSlot: '09:00',
    isRequired: false,
    order: 4,
  },

  // Section C: MONITORING BERKALA (Setiap 2 Jam)
  {
    checklistType: 'FRAUD_COMPLIANCE',
    shiftType: 'SHIFT_SIANG',
    section: 'C',
    sectionTitle: 'MONITORING BERKALA (Setiap 2 Jam)',
    itemNumber: 1,
    title: 'Review FDS alerts real-time',
    toolSystem: 'FDS Dashboard',
    timeSlot: '10:00',
    isRequired: true,
    order: 1,
  },
  {
    checklistType: 'FRAUD_COMPLIANCE',
    shiftType: 'SHIFT_SIANG',
    section: 'C',
    sectionTitle: 'MONITORING BERKALA (Setiap 2 Jam)',
    itemNumber: 2,
    title: 'Monitor transaksi suspicious pattern',
    toolSystem: 'FDS Dashboard',
    timeSlot: '10:00',
    isRequired: true,
    order: 2,
  },
  {
    checklistType: 'FRAUD_COMPLIANCE',
    shiftType: 'SHIFT_SIANG',
    section: 'C',
    sectionTitle: 'MONITORING BERKALA (Setiap 2 Jam)',
    itemNumber: 3,
    title: 'Cek notifikasi fraud dari switching',
    toolSystem: 'Email/Dashboard',
    timeSlot: '10:00',
    isRequired: true,
    order: 3,
  },
  {
    checklistType: 'FRAUD_COMPLIANCE',
    shiftType: 'SHIFT_SIANG',
    section: 'C',
    sectionTitle: 'MONITORING BERKALA (Setiap 2 Jam)',
    itemNumber: 4,
    title: 'Review high-value transaction alerts',
    toolSystem: 'FDS Dashboard',
    timeSlot: '10:00',
    isRequired: true,
    order: 4,
  },

  // Section D: PENUTUPAN SHIFT (18:00 - 20:00)
  {
    checklistType: 'FRAUD_COMPLIANCE',
    shiftType: 'SHIFT_SIANG',
    section: 'D',
    sectionTitle: 'PENUTUPAN SHIFT (18:00 - 20:00)',
    itemNumber: 1,
    title: 'Kompilasi fraud cases hari ini',
    toolSystem: 'Case Management',
    timeSlot: '18:00',
    isRequired: true,
    order: 1,
  },
  {
    checklistType: 'FRAUD_COMPLIANCE',
    shiftType: 'SHIFT_SIANG',
    section: 'D',
    sectionTitle: 'PENUTUPAN SHIFT (18:00 - 20:00)',
    itemNumber: 2,
    title: 'Update daily fraud report',
    toolSystem: 'Report System',
    timeSlot: '18:00',
    isRequired: true,
    order: 2,
  },
  {
    checklistType: 'FRAUD_COMPLIANCE',
    shiftType: 'SHIFT_SIANG',
    section: 'D',
    sectionTitle: 'PENUTUPAN SHIFT (18:00 - 20:00)',
    itemNumber: 3,
    title: 'Siapkan handover untuk shift malam',
    toolSystem: 'ServiceDesk',
    timeSlot: '19:00',
    isRequired: true,
    order: 3,
  },
  {
    checklistType: 'FRAUD_COMPLIANCE',
    shiftType: 'SHIFT_SIANG',
    section: 'D',
    sectionTitle: 'PENUTUPAN SHIFT (18:00 - 20:00)',
    itemNumber: 4,
    title: 'Serah terima ke PIC Shift Malam',
    description: 'Brief pending cases',
    timeSlot: '20:00',
    isRequired: true,
    order: 4,
  },
];

// ============================================
// FRAUD_COMPLIANCE - SHIFT_MALAM (20:00-08:00)
// ============================================

const FRAUD_SHIFT_MALAM_TEMPLATES: TemplateData[] = [
  // Section A: SERAH TERIMA & MULAI SHIFT (20:00 - 20:30)
  {
    checklistType: 'FRAUD_COMPLIANCE',
    shiftType: 'SHIFT_MALAM',
    section: 'A',
    sectionTitle: 'SERAH TERIMA & MULAI SHIFT (20:00 - 20:30)',
    itemNumber: 1,
    title: 'Terima handover dari PIC Shift Siang',
    description: 'Review pending fraud cases',
    timeSlot: '20:00',
    isRequired: true,
    order: 1,
  },
  {
    checklistType: 'FRAUD_COMPLIANCE',
    shiftType: 'SHIFT_MALAM',
    section: 'A',
    sectionTitle: 'SERAH TERIMA & MULAI SHIFT (20:00 - 20:30)',
    itemNumber: 2,
    title: 'Review fraud cases dari shift siang',
    toolSystem: 'Case Management',
    timeSlot: '20:00',
    isRequired: true,
    order: 2,
  },
  {
    checklistType: 'FRAUD_COMPLIANCE',
    shiftType: 'SHIFT_MALAM',
    section: 'A',
    sectionTitle: 'SERAH TERIMA & MULAI SHIFT (20:00 - 20:30)',
    itemNumber: 3,
    title: 'Verifikasi status FDS system',
    toolSystem: 'FDS Dashboard',
    timeSlot: '20:00',
    isRequired: true,
    order: 3,
  },
  {
    checklistType: 'FRAUD_COMPLIANCE',
    shiftType: 'SHIFT_MALAM',
    section: 'A',
    sectionTitle: 'SERAH TERIMA & MULAI SHIFT (20:00 - 20:30)',
    itemNumber: 4,
    title: 'Konfirmasi buddy on-call tersedia',
    toolSystem: 'WhatsApp',
    timeSlot: '20:00',
    isRequired: true,
    order: 4,
  },

  // Section B: MONITORING RUTIN MALAM (Setiap 2 Jam)
  {
    checklistType: 'FRAUD_COMPLIANCE',
    shiftType: 'SHIFT_MALAM',
    section: 'B',
    sectionTitle: 'MONITORING RUTIN MALAM (Setiap 2 Jam)',
    itemNumber: 1,
    title: 'Review FDS alerts',
    toolSystem: 'FDS Dashboard',
    timeSlot: '22:00',
    isRequired: true,
    order: 1,
  },
  {
    checklistType: 'FRAUD_COMPLIANCE',
    shiftType: 'SHIFT_MALAM',
    section: 'B',
    sectionTitle: 'MONITORING RUTIN MALAM (Setiap 2 Jam)',
    itemNumber: 2,
    title: 'Monitor transaksi suspicious overnight',
    toolSystem: 'FDS Dashboard',
    timeSlot: '22:00',
    isRequired: true,
    order: 2,
  },
  {
    checklistType: 'FRAUD_COMPLIANCE',
    shiftType: 'SHIFT_MALAM',
    section: 'B',
    sectionTitle: 'MONITORING RUTIN MALAM (Setiap 2 Jam)',
    itemNumber: 3,
    title: 'Cek notifikasi fraud dari switching',
    toolSystem: 'Email/Dashboard',
    timeSlot: '22:00',
    isRequired: true,
    order: 3,
  },
  {
    checklistType: 'FRAUD_COMPLIANCE',
    shiftType: 'SHIFT_MALAM',
    section: 'B',
    sectionTitle: 'MONITORING RUTIN MALAM (Setiap 2 Jam)',
    itemNumber: 4,
    title: 'Monitor high-risk transaction patterns',
    toolSystem: 'FDS Dashboard',
    timeSlot: '22:00',
    isRequired: true,
    order: 4,
  },

  // Section C: MONITORING TENGAH MALAM (00:00 - 04:00)
  {
    checklistType: 'FRAUD_COMPLIANCE',
    shiftType: 'SHIFT_MALAM',
    section: 'C',
    sectionTitle: 'MONITORING TENGAH MALAM (00:00 - 04:00)',
    itemNumber: 1,
    title: 'Deep analysis overnight fraud patterns',
    toolSystem: 'FDS Dashboard',
    timeSlot: '00:00',
    isRequired: true,
    order: 1,
  },
  {
    checklistType: 'FRAUD_COMPLIANCE',
    shiftType: 'SHIFT_MALAM',
    section: 'C',
    sectionTitle: 'MONITORING TENGAH MALAM (00:00 - 04:00)',
    itemNumber: 2,
    title: 'Review LTKM status updates',
    toolSystem: 'LTKM System',
    timeSlot: '02:00',
    isRequired: true,
    order: 2,
  },
  {
    checklistType: 'FRAUD_COMPLIANCE',
    shiftType: 'SHIFT_MALAM',
    section: 'C',
    sectionTitle: 'MONITORING TENGAH MALAM (00:00 - 04:00)',
    itemNumber: 3,
    title: 'Cek batch processing fraud detection results',
    toolSystem: 'FDS Dashboard',
    timeSlot: '04:00',
    isRequired: true,
    order: 3,
  },

  // Section D: PERSIAPAN AKHIR SHIFT (06:00 - 08:00)
  {
    checklistType: 'FRAUD_COMPLIANCE',
    shiftType: 'SHIFT_MALAM',
    section: 'D',
    sectionTitle: 'PERSIAPAN AKHIR SHIFT (06:00 - 08:00)',
    itemNumber: 1,
    title: 'Final fraud monitoring check',
    toolSystem: 'FDS Dashboard',
    timeSlot: '06:00',
    isRequired: true,
    order: 1,
  },
  {
    checklistType: 'FRAUD_COMPLIANCE',
    shiftType: 'SHIFT_MALAM',
    section: 'D',
    sectionTitle: 'PERSIAPAN AKHIR SHIFT (06:00 - 08:00)',
    itemNumber: 2,
    title: 'Kompilasi overnight fraud events',
    toolSystem: 'Case Management',
    timeSlot: '06:00',
    isRequired: true,
    order: 2,
  },
  {
    checklistType: 'FRAUD_COMPLIANCE',
    shiftType: 'SHIFT_MALAM',
    section: 'D',
    sectionTitle: 'PERSIAPAN AKHIR SHIFT (06:00 - 08:00)',
    itemNumber: 3,
    title: 'Siapkan summary untuk handover pagi',
    timeSlot: '07:00',
    isRequired: true,
    order: 3,
  },
  {
    checklistType: 'FRAUD_COMPLIANCE',
    shiftType: 'SHIFT_MALAM',
    section: 'D',
    sectionTitle: 'PERSIAPAN AKHIR SHIFT (06:00 - 08:00)',
    itemNumber: 4,
    title: 'Serah terima ke PIC Shift Siang',
    description: 'Brief pending fraud cases',
    timeSlot: '08:00',
    isRequired: true,
    order: 4,
  },
];

// ============================================
// MAIN SEED FUNCTION
// ============================================

async function seedChecklistV2TemplatesNew() {
  console.log('🌱 Starting NEW Checklist V2 template seed...');
  console.log('📋 Using 3 Checklist Types: IT_INFRASTRUKTUR, KEAMANAN_SIBER, FRAUD_COMPLIANCE');
  console.log('📋 Using 2 Shift Types: SHIFT_SIANG, SHIFT_MALAM');

  // Combine all templates
  const allTemplates = [
    ...IT_INFRA_SHIFT_SIANG_TEMPLATES,
    ...IT_INFRA_SHIFT_MALAM_TEMPLATES,
    ...KKS_SHIFT_SIANG_TEMPLATES,
    ...KKS_SHIFT_MALAM_TEMPLATES,
    ...FRAUD_SHIFT_SIANG_TEMPLATES,
    ...FRAUD_SHIFT_MALAM_TEMPLATES,
  ];

  console.log(`📋 Total templates to seed: ${allTemplates.length}`);

  // Clear existing templates
  console.log('🗑️  Clearing existing V2 templates...');
  await prisma.checklistTemplateV2.deleteMany({});

  // Insert templates
  let created = 0;
  for (const template of allTemplates) {
    await prisma.checklistTemplateV2.create({
      data: {
        checklistType: template.checklistType,
        shiftType: template.shiftType,
        section: template.section,
        sectionTitle: template.sectionTitle,
        itemNumber: template.itemNumber,
        title: template.title,
        description: template.description,
        toolSystem: template.toolSystem,
        timeSlot: template.timeSlot,
        isRequired: template.isRequired,
        order: template.order,
        isActive: true,
      },
    });
    created++;
  }

  console.log(`✅ Created ${created} templates`);

  // Summary by checklistType and shift type
  const summary = await prisma.checklistTemplateV2.groupBy({
    by: ['checklistType', 'shiftType'],
    _count: true,
  });

  console.log('\n📊 Summary by ChecklistType/Shift:');
  for (const item of summary) {
    console.log(`   ${item.checklistType} / ${item.shiftType}: ${item._count} templates`);
  }

  console.log('\n✅ NEW Checklist V2 template seed completed!');
}

// Run seed
seedChecklistV2TemplatesNew()
  .catch((e) => {
    console.error('❌ Seed error:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
