// Auto-generated version information from git
// Generated at: 2025-11-04T01:56:19.152Z
// DO NOT EDIT THIS FILE MANUALLY - It will be overwritten

export const APP_VERSION = {
  version: '2.8.0',
  commit: '50c55a7',
  branch: 'main',
  buildNumber: 331,
  buildDate: '2025-11-04',
  environment: process.env.NODE_ENV || 'development',
  copyright: '© 2025 Bank SulutGo',
  lastCommit: {
    message: `feat: Add Monthly Reports button and merge strategy documentation`,
    date: '2025-11-04 09:52:00 +0800',
    hash: '50c55a7'
  },
  isDirty: false,
  tag: ''
};

// Get formatted version string
export function getVersionString(): string {
  const { version } = APP_VERSION;
  return `v${version}`;
}

// Get full version info for debugging
export function getFullVersionInfo(): string {
  const { version, buildNumber, branch, buildDate } = APP_VERSION;
  return `Version ${version} | Build #${buildNumber} | Branch: ${branch} | Built: ${buildDate}`;
}

// Get commit info
export function getCommitInfo(): string {
  const { lastCommit } = APP_VERSION;
  const date = new Date(lastCommit.date);
  const formattedDate = date.toLocaleDateString('en-US', { 
    year: 'numeric', 
    month: 'short', 
    day: 'numeric' 
  });
  return `${lastCommit.message.substring(0, 50)}${lastCommit.message.length > 50 ? '...' : ''} (${formattedDate})`;
}

// Version history based on commit messages
export const VERSION_HISTORY = [
  {
    version: APP_VERSION.version,
    date: APP_VERSION.buildDate,
    commit: APP_VERSION.commit,
    message: APP_VERSION.lastCommit.message
  }
];
