// Auto-generated version information from git
// Generated at: 2025-10-11T12:03:54.859Z
// DO NOT EDIT THIS FILE MANUALLY - It will be overwritten

export const APP_VERSION = {
  version: '2.7.0',
  commit: '168e8cf',
  branch: 'main',
  buildNumber: 256,
  buildDate: '2025-10-11',
  environment: process.env.NODE_ENV || 'development',
  copyright: '© 2025 Bank SulutGo',
  lastCommit: {
    message: `feat: Redesign sidebar profile section with warm amber theme`,
    date: '2025-10-11 19:46:35 +0800',
    hash: '168e8cf'
  },
  isDirty: false,
  tag: ''
};

// Get formatted version string
export function getVersionString(): string {
  const { version } = APP_VERSION;
  return `v${version}`;
}

// Get full version info for debugging
export function getFullVersionInfo(): string {
  const { version, buildNumber, branch, buildDate } = APP_VERSION;
  return `Version ${version} | Build #${buildNumber} | Branch: ${branch} | Built: ${buildDate}`;
}

// Get commit info
export function getCommitInfo(): string {
  const { lastCommit } = APP_VERSION;
  const date = new Date(lastCommit.date);
  const formattedDate = date.toLocaleDateString('en-US', { 
    year: 'numeric', 
    month: 'short', 
    day: 'numeric' 
  });
  return `${lastCommit.message.substring(0, 50)}${lastCommit.message.length > 50 ? '...' : ''} (${formattedDate})`;
}

// Version history based on commit messages
export const VERSION_HISTORY = [
  {
    version: APP_VERSION.version,
    date: APP_VERSION.buildDate,
    commit: APP_VERSION.commit,
    message: APP_VERSION.lastCommit.message
  }
];
