// Auto-generated version information from git
// Generated at: 2025-10-10T05:51:37.471Z
// DO NOT EDIT THIS FILE MANUALLY - It will be overwritten

export const APP_VERSION = {
  version: '2.7.0',
  commit: '6dd1e7b',
  branch: 'main',
  buildNumber: 244,
  buildDate: '2025-10-10',
  environment: process.env.NODE_ENV || 'development',
  copyright: '© 2025 Bank SulutGo',
  lastCommit: {
    message: `fix: Use branch IDs instead of codes for filtering`,
    date: '2025-10-09 11:54:06 +0800',
    hash: '6dd1e7b'
  },
  isDirty: false,
  tag: ''
};

// Get formatted version string
export function getVersionString(): string {
  const { version } = APP_VERSION;
  return `v${version}`;
}

// Get full version info for debugging
export function getFullVersionInfo(): string {
  const { version, buildNumber, branch, buildDate } = APP_VERSION;
  return `Version ${version} | Build #${buildNumber} | Branch: ${branch} | Built: ${buildDate}`;
}

// Get commit info
export function getCommitInfo(): string {
  const { lastCommit } = APP_VERSION;
  const date = new Date(lastCommit.date);
  const formattedDate = date.toLocaleDateString('en-US', { 
    year: 'numeric', 
    month: 'short', 
    day: 'numeric' 
  });
  return `${lastCommit.message.substring(0, 50)}${lastCommit.message.length > 50 ? '...' : ''} (${formattedDate})`;
}

// Version history based on commit messages
export const VERSION_HISTORY = [
  {
    version: APP_VERSION.version,
    date: APP_VERSION.buildDate,
    commit: APP_VERSION.commit,
    message: APP_VERSION.lastCommit.message
  }
];
