import { NextRequest, NextResponse } from 'next/server';
import { auth } from '@/lib/auth';
import { prisma } from '@/lib/prisma';
import { ShiftType } from '@prisma/client';

/**
 * POST /api/shifts/schedules/builder
 * Create a blank shift schedule for manual building
 *
 * Required: MANAGER or ADMIN role
 */
export async function POST(request: NextRequest) {
  try {
    const session = await auth();

    if (!session?.user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    // Check role permissions
    if (!['MANAGER', 'MANAGER_IT', 'ADMIN'].includes(session.user.role)) {
      return NextResponse.json(
        { error: 'Insufficient permissions. Manager, IT Manager, or Admin role required.' },
        { status: 403 }
      );
    }

    const body = await request.json();
    const { branchId, month, year } = body;

    // Validate inputs
    if (!branchId || !month || !year) {
      return NextResponse.json(
        { error: 'branchId, month, and year are required' },
        { status: 400 }
      );
    }

    if (month < 1 || month > 12) {
      return NextResponse.json(
        { error: 'Month must be between 1 and 12' },
        { status: 400 }
      );
    }

    // Check if branch exists
    const branch = await prisma.branch.findUnique({
      where: { id: branchId },
    });

    if (!branch) {
      return NextResponse.json({ error: 'Branch not found' }, { status: 404 });
    }

    // Check if there's already a published schedule for this month
    const publishedSchedule = await prisma.shiftSchedule.findFirst({
      where: {
        branchId,
        month,
        year,
        status: 'PUBLISHED',
      },
    });

    // Note: Multiple schedules can exist for the same month (drafts, generated)
    // but only one can be PUBLISHED at a time

    // Create blank schedule
    const schedule = await prisma.shiftSchedule.create({
      data: {
        branchId,
        month,
        year,
        status: 'GENERATED',
        generatedAt: new Date(),
        createdBy: session.user.id,
        generationRules: {
          targetNightsPerMonth: 5,
          minGapBetweenNights: 3,
          requireOffAfterNight: true,
          weekdayNightCount: 1,
          weekendDayCount: 2,
          weekendNightCount: 0,
          manuallyCreated: true,
        },
      },
    });

    // Create LEAVE assignments for approved leave requests in this month
    const monthStart = new Date(year, month - 1, 1);
    const monthEnd = new Date(year, month, 0);

    const leaveRequests = await prisma.leaveRequest.findMany({
      where: {
        staffProfile: {
          user: {
            branchId,
          },
        },
        status: 'APPROVED',
        OR: [
          {
            AND: [
              { startDate: { lte: monthEnd } },
              { endDate: { gte: monthStart } },
            ],
          },
        ],
      },
      include: {
        staffProfile: true,
      },
    });

    // Create LEAVE assignments for each leave request
    const leaveAssignments = [];
    for (const leave of leaveRequests) {
      const currentDate = new Date(Math.max(leave.startDate.getTime(), monthStart.getTime()));
      const endDate = new Date(Math.min(leave.endDate.getTime(), monthEnd.getTime()));

      while (currentDate <= endDate) {
        leaveAssignments.push({
          scheduleId: schedule.id,
          staffProfileId: leave.staffProfileId,
          date: new Date(currentDate),
          shiftType: ShiftType.LEAVE,
          isAutoGenerated: true,
        });
        currentDate.setDate(currentDate.getDate() + 1);
      }
    }

    if (leaveAssignments.length > 0) {
      await prisma.shiftAssignment.createMany({
        data: leaveAssignments,
      });
    }

    return NextResponse.json({
      success: true,
      data: {
        scheduleId: schedule.id,
        branchId,
        month,
        year,
        status: schedule.status,
        leaveAssignmentsCreated: leaveAssignments.length,
      },
    });
  } catch (error: any) {
    console.error('Error creating blank schedule:', error);
    return NextResponse.json(
      { error: error.message || 'Failed to create blank schedule' },
      { status: 500 }
    );
  }
}
