import { NextRequest, NextResponse } from 'next/server';
import { getServerSession } from 'next-auth';
import { authOptions } from '@/app/api/auth/[...nextauth]/route';
import { prisma } from '@/lib/prisma';
import { ShiftGenerator } from '@/lib/shift-generator';

/**
 * POST /api/shifts/schedules/generate
 * Generate shift schedule for a branch and month
 *
 * Required: MANAGER or ADMIN role
 */
export async function POST(request: NextRequest) {
  try {
    const session = await getServerSession(authOptions);

    if (!session?.user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    // Check role permissions
    if (!['MANAGER', 'MANAGER_IT', 'ADMIN'].includes(session.user.role)) {
      return NextResponse.json(
        { error: 'Insufficient permissions. Manager, IT Manager, or Admin role required.' },
        { status: 403 }
      );
    }

    const body = await request.json();
    const { branchId, month, year, holidayDates = [] } = body;

    // Validate inputs
    if (!branchId || !month || !year) {
      return NextResponse.json(
        { error: 'branchId, month, and year are required' },
        { status: 400 }
      );
    }

    if (month < 1 || month > 12) {
      return NextResponse.json(
        { error: 'Month must be between 1 and 12' },
        { status: 400 }
      );
    }

    // Check if branch exists
    const branch = await prisma.branch.findUnique({
      where: { id: branchId },
    });

    if (!branch) {
      return NextResponse.json({ error: 'Branch not found' }, { status: 404 });
    }

    // Check if schedule already exists
    const existingSchedule = await prisma.shiftSchedule.findUnique({
      where: {
        branchId_month_year: {
          branchId,
          month,
          year,
        },
      },
    });

    if (existingSchedule) {
      return NextResponse.json(
        { error: 'Schedule already exists for this month. Please delete it first or use update.' },
        { status: 409 }
      );
    }

    // Parse holiday dates
    const holidays = holidayDates.map((d: string) => new Date(d));

    // Generate schedule
    const generator = new ShiftGenerator(prisma);
    const result = await generator.generateSchedule(branchId, month, year, holidays);

    // Create schedule record
    const schedule = await prisma.shiftSchedule.create({
      data: {
        branchId,
        month,
        year,
        status: 'GENERATED',
        generatedAt: new Date(),
        createdBy: session.user.id,
        generationRules: {
          targetNightsPerMonth: 5,
          minGapBetweenNights: 3,
          requireOffAfterNight: true,
          weekdayNightCount: 1,
          weekendDayCount: 2,
          weekendNightCount: 3,
        },
      },
    });

    // Create shift assignments
    const assignments = await prisma.shiftAssignment.createMany({
      data: result.assignments.map((a) => ({
        scheduleId: schedule.id,
        staffProfileId: a.staffProfileId,
        date: a.date,
        shiftType: a.shiftType,
        isAutoGenerated: a.isAutoGenerated,
      })),
    });

    // Create on-call assignments
    const onCallCount = await prisma.onCallAssignment.createMany({
      data: result.onCallAssignments.map((a) => ({
        scheduleId: schedule.id,
        staffProfileId: a.staffProfileId,
        date: a.date,
        reason: a.reason,
      })),
    });

    // Create holiday records
    if (holidays.length > 0) {
      await prisma.holiday.createMany({
        data: holidays.map((date) => ({
          scheduleId: schedule.id,
          name: 'Holiday',
          date,
          holidayType: 'PUBLIC',
        })),
      });
    }

    return NextResponse.json({
      success: true,
      data: {
        scheduleId: schedule.id,
        branchId,
        month,
        year,
        assignmentsCreated: assignments.count,
        onCallAssignmentsCreated: onCallCount.count,
        stats: result.stats,
      },
    });
  } catch (error: any) {
    console.error('Error generating shift schedule:', error);
    return NextResponse.json(
      { error: error.message || 'Failed to generate shift schedule' },
      { status: 500 }
    );
  }
}