import { NextRequest, NextResponse } from 'next/server';
import { auth } from '@/lib/auth';
import { prisma } from '@/lib/prisma';

/**
 * PATCH /api/shifts/leave-requests/[leaveRequestId]
 * Approve or reject leave request
 */
export async function PATCH(
  request: NextRequest,
  { params }: { params: { leaveRequestId: string } }
) {
  try {
    const session = await auth();

    if (!session?.user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    if (!['MANAGER', 'MANAGER_IT', 'ADMIN'].includes(session.user.role)) {
      return NextResponse.json(
        { error: 'Insufficient permissions. Manager, IT Manager, or Admin role required.' },
        { status: 403 }
      );
    }

    const body = await request.json();
    const { status, rejectionReason } = body;

    if (!status || !['APPROVED', 'REJECTED', 'CANCELLED'].includes(status)) {
      return NextResponse.json(
        { error: 'Valid status is required (APPROVED, REJECTED, or CANCELLED)' },
        { status: 400 }
      );
    }

    const data: any = { status };

    if (status === 'APPROVED') {
      data.approvedBy = session.user.id;
      data.approvedAt = new Date();
    } else if (status === 'REJECTED') {
      if (!rejectionReason) {
        return NextResponse.json(
          { error: 'Rejection reason is required' },
          { status: 400 }
        );
      }
      data.rejectedBy = session.user.id;
      data.rejectedAt = new Date();
      data.rejectionReason = rejectionReason;
    }

    const leaveRequest = await prisma.leaveRequest.update({
      where: { id: params.leaveRequestId },
      data,
      include: {
        staffProfile: {
          include: {
            user: {
              select: {
                id: true,
                name: true,
                email: true,
              },
            },
          },
        },
      },
    });

    // If approved, mark shifts as LEAVE in relevant schedules
    if (status === 'APPROVED') {
      const startDate = leaveRequest.startDate;
      const endDate = leaveRequest.endDate;

      // Find all schedules that overlap with this leave period
      const schedules = await prisma.shiftSchedule.findMany({
        where: {
          branchId: leaveRequest.staffProfile.branchId,
          OR: [
            {
              AND: [
                { year: startDate.getFullYear() },
                { month: { gte: startDate.getMonth() + 1 } },
              ],
            },
            {
              AND: [
                { year: endDate.getFullYear() },
                { month: { lte: endDate.getMonth() + 1 } },
              ],
            },
          ],
        },
      });

      // Update or create LEAVE assignments for each day
      for (const schedule of schedules) {
        const current = new Date(startDate);
        while (current <= endDate) {
          if (
            current.getFullYear() === schedule.year &&
            current.getMonth() + 1 === schedule.month
          ) {
            await prisma.shiftAssignment.upsert({
              where: {
                scheduleId_staffProfileId_date: {
                  scheduleId: schedule.id,
                  staffProfileId: leaveRequest.staffProfileId,
                  date: new Date(current),
                },
              },
              create: {
                scheduleId: schedule.id,
                staffProfileId: leaveRequest.staffProfileId,
                date: new Date(current),
                shiftType: 'LEAVE',
                isAutoGenerated: false,
              },
              update: {
                shiftType: 'LEAVE',
                isManualOverride: true,
              },
            });
          }
          current.setDate(current.getDate() + 1);
        }
      }
    }

    return NextResponse.json({
      success: true,
      data: leaveRequest,
      message: `Leave request ${status.toLowerCase()} successfully`,
    });
  } catch (error: any) {
    console.error('Error updating leave request:', error);
    return NextResponse.json(
      { error: error.message || 'Failed to update leave request' },
      { status: 500 }
    );
  }
}